repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  - repo: local
    hooks:
      - id: claude-attribution
        name: Check for Claude attribution
        description: Checks if files containing AI-generated code have proper attribution
        entry: scripts/hooks/check_claude_attribution.py
        language: python
        types: [text]
