/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Air conditioner.glb -o /workspaces/windgapacademy/components/CityPackModels/Air conditioner.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Air conditioner.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Air_Conditioner.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/Air conditioner.glb')
