/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Air Vent.glb -o /workspaces/windgapacademy/components/CityPackModels/Air Vent.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Air Vent.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["AirVent_Cube-Mesh"].geometry} material={materials.Base} />
      <mesh geometry={nodes["AirVent_Cube-Mesh_1"].geometry} material={materials.Screws} />
    </group>
  );
}

useGLTF.preload("/Air Vent.glb");
