/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Alpaca.glb -o /workspaces/windgapacademy/components/CityPackModels/Alpaca.jsx
*/

import { useGLTF, useAnimations } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import React from "react";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/Alpaca.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="AnimalArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group name="Alpaca" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Alpaca_1"
              geometry={nodes.Alpaca_1.geometry}
              material={materials.Main_Light}
              skeleton={nodes.Alpaca_1.skeleton}
            />
            <skinnedMesh
              name="Alpaca_2"
              geometry={nodes.Alpaca_2.geometry}
              material={materials.Main}
              skeleton={nodes.Alpaca_2.skeleton}
            />
            <skinnedMesh
              name="Alpaca_3"
              geometry={nodes.Alpaca_3.geometry}
              material={materials.Main_Dark}
              skeleton={nodes.Alpaca_3.skeleton}
            />
            <skinnedMesh
              name="Alpaca_4"
              geometry={nodes.Alpaca_4.geometry}
              material={materials.Muzzle}
              skeleton={nodes.Alpaca_4.skeleton}
            />
            <skinnedMesh
              name="Alpaca_5"
              geometry={nodes.Alpaca_5.geometry}
              material={materials.Hooves}
              skeleton={nodes.Alpaca_5.skeleton}
            />
            <skinnedMesh
              name="Alpaca_6"
              geometry={nodes.Alpaca_6.geometry}
              material={materials.Eyes_Black}
              skeleton={nodes.Alpaca_6.skeleton}
            />
            <skinnedMesh
              name="Alpaca_7"
              geometry={nodes.Alpaca_7.geometry}
              material={materials.Eyes_White}
              skeleton={nodes.Alpaca_7.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Alpaca.glb");
