/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Analog clock.glb -o /workspaces/windgapacademy/components/CityPackModels/Analog clock.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Analog clock.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Analog_Cock.geometry} material={materials.Mat} />
    </group>
  );
}

useGLTF.preload("/Analog clock.glb");
