/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Angle Brush.glb -o /workspaces/windgapacademy/components/CityPackModels/Angle Brush.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Angle Brush.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.AngleBrush1_1.geometry} material={materials.Wood1AngleBrush1} />
        <mesh geometry={nodes.AngleBrush1_2.geometry} material={materials.Bristles1AngleBrush1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Angle Brush.glb')
