/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Animated Woman.glb -o /workspaces/windgapacademy/components/CityPackModels/Animated Woman.jsx 
*/

import { useGLTF, useAnimations, useGraph } from "@react-three/drei";

import React, { useEffect } from "react";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/Animated Woman.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions, names } = useAnimations(animations, group);
  
  // Play first animation if available
  useEffect(() => {
    if (names.length > 0 && actions[names[0]]) {
      actions[names[0]].reset().fadeIn(0.5).play();
    }
    return () => names.forEach(name => actions[name]?.fadeOut(0.5));
  }, [actions, names]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]}>
            <primitive object={nodes.Hips} />
          </group>
          <skinnedMesh
            name="Woman"
            geometry={nodes.Woman.geometry}
            material={materials.Material}
            skeleton={nodes.Woman.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Animated Woman.glb");
