/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Apple Half.glb -o /workspaces/windgapacademy/components/CityPackModels/Apple Half.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Apple Half.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.appleHalf_1.geometry} material={materials.red} />
      <mesh geometry={nodes.appleHalf_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.appleHalf_1_2.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.appleHalf_1_3.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.appleHalf_1_4.geometry} material={materials._defaultMat} />
    </group>
  );
}

useGLTF.preload("/Apple Half.glb");
