/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/ATM.glb -o /workspaces/windgapacademy/components/CityPackModels/ATM.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/ATM.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.007, 0.125, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={48}>
        <mesh geometry={nodes.ATM_1.geometry} material={materials.gray_shade1} />
        <mesh geometry={nodes.ATM_2.geometry} material={materials.blue} />
        <mesh geometry={nodes.ATM_3.geometry} material={materials.screen} />
        <mesh geometry={nodes.ATM_4.geometry} material={materials.white} />
        <mesh geometry={nodes.ATM_5.geometry} material={materials.gray_shade2} />
        <mesh geometry={nodes.ATM_6.geometry} material={materials.blue_shade2} />
      </group>
    </group>
  );
}

useGLTF.preload("/ATM.glb");
