/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Avocado Half.glb -o /workspaces/windgapacademy/components/CityPackModels/Avocado Half.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Avocado Half.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pit.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.avocadoHalf_1.geometry} material={materials.green} />
      <mesh geometry={nodes.avocadoHalf_1_1.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.avocadoHalf_1_2.geometry} material={materials.brownDark} />
    </group>
  );
}

useGLTF.preload("/Avocado Half.glb");
