/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Backpack.glb -o /workspaces/windgapacademy/components/CityPackModels/Backpack.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Backpack.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Backpack_Cube006-Mesh"].geometry} material={materials.Backpack} />
      <mesh geometry={nodes["Backpack_Cube006-Mesh_1"].geometry} material={materials.Silver} />
      <mesh geometry={nodes["Backpack_Cube006-Mesh_2"].geometry} material={materials.Brown2} />
    </group>
  );
}

useGLTF.preload("/Backpack.glb");
