/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bacon.glb -o /workspaces/windgapacademy/components/CityPackModels/Bacon.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bacon.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bacon_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.bacon_1_1.geometry} material={materials.brownDark} />
    </group>
  );
}

useGLTF.preload("/Bacon.glb");
