/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bamboo.glb -o /workspaces/windgapacademy/components/CityPackModels/Bamboo.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bamboo.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BlackBamboo_1.geometry} material={materials.BarkBlackBamboo} />
      <mesh geometry={nodes.BlackBamboo_2.geometry} material={materials.LeafBlackBamboo} />
    </group>
  );
}

useGLTF.preload("/Bamboo.glb");
