/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Banana.glb -o /workspaces/windgapacademy/components/CityPackModels/Banana.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Banana.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.banana_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.banana_1_1.geometry} material={materials.yellow} />
    </group>
  );
}

useGLTF.preload("/Banana.glb");
