/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bar Stool.glb -o /workspaces/windgapacademy/components/CityPackModels/Bar Stool.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bar Stool.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.stoolBar_2.geometry} material={materials.wood} />
      <mesh geometry={nodes.stoolBar_2_1.geometry} material={materials.carpet} />
      <mesh geometry={nodes.stoolBar_3.geometry} material={materials.carpet} />
      <mesh geometry={nodes.stoolBar_3_1.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/Bar Stool.glb')
