/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Barbell.glb -o /workspaces/windgapacademy/components/CityPackModels/Barbell.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Barbell.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Barbell1_1.geometry} material={materials.Iron1Barbell1} />
        <mesh geometry={nodes.Barbell1_2.geometry} material={materials.Steel1Barbell1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Barbell.glb')
