/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Barn.glb -o /workspaces/windgapacademy/components/CityPackModels/Barn.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Barn.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Barn.geometry} material={materials.Diffuse_color} scale={100} />
    </group>
  );
}

useGLTF.preload("/Barn.glb");
