/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Barstool.glb -o /workspaces/windgapacademy/components/CityPackModels/Barstool.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Barstool.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box001.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box002.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box003.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box004.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box005.geometry} material={materials['02___Default']} />
      <mesh geometry={nodes.Box006.geometry} material={materials['02___Default']} />
      <mesh geometry={nodes.Box007.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box008.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box009.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box010.geometry} material={materials._crayfishdiffuse} />
    </group>
  )
}

useGLTF.preload('/Barstool.glb')
