/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bathroom Toilet Paper.glb -o /workspaces/windgapacademy/components/CityPackModels/Bathroom Toilet Paper.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bathroom Toilet Paper.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Bathroom_ToiletPaper_1.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Bathroom_ToiletPaper_2.geometry} material={materials.White} />
        <mesh geometry={nodes.Bathroom_ToiletPaper_3.geometry} material={materials.LightMetal} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bathroom Toilet Paper.glb')
