/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bedside Lamp.glb -o /workspaces/windgapacademy/components/CityPackModels/Bedside Lamp.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bedside Lamp.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.BedsideLamp1_1.geometry} material={materials.ShadeBedsideLamp1} />
        <mesh geometry={nodes.BedsideLamp1_2.geometry} material={materials.LightBedsideLamp1} />
        <mesh geometry={nodes.BedsideLamp1_3.geometry} material={materials.MetalBedsideLamp1} />
      </group>
    </group>
  );
}

useGLTF.preload("/Bedside Lamp.glb");
