/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Beet.glb -o /workspaces/windgapacademy/components/CityPackModels/Beet.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Beet.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.beet_1.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.beet_1_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.beet_1_2.geometry} material={materials.green} />
    </group>
  );
}

useGLTF.preload("/Beet.glb");
