/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bicycle.glb -o /workspaces/windgapacademy/components/CityPackModels/Bicycle.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bicycle.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bike_mesh.geometry} material={materials.Bike_mat1} />
    </group>
  );
}

useGLTF.preload("/Bicycle.glb");
