/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bilby.glb -o /workspaces/windgapacademy/components/CityPackModels/Bilby.jsx 
*/

import { useGLTF, useAnimations, useGraph } from "@react-three/drei";

import React, { useEffect } from "react";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/Bilby.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions, names } = useAnimations(animations, group);
  
  // Play first animation if available
  useEffect(() => {
    if (names.length > 0 && actions[names[0]]) {
      actions[names[0]].reset().fadeIn(0.5).play();
    }
    return () => names.forEach(name => actions[name]?.fadeOut(0.5));
  }, [actions, names]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Master_Bone} />
          </group>
          <skinnedMesh
            name="bilby"
            geometry={nodes.bilby.geometry}
            material={materials.bilby}
            skeleton={nodes.bilby.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="EyeL"
              geometry={nodes.EyeL.geometry}
              material={materials["Material.001"]}
              skeleton={nodes.EyeL.skeleton}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
            <skinnedMesh
              name="EyeR"
              geometry={nodes.EyeR.geometry}
              material={materials.Material}
              skeleton={nodes.EyeR.skeleton}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </skinnedMesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Bilby.glb");
