/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Billboard.glb -o /workspaces/windgapacademy/components/CityPackModels/Billboard.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Billboard.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.b.geometry} material={materials.lambert3SG} />
      <mesh geometry={nodes.a.geometry} material={materials.lambert3SG} />
    </group>
  );
}

useGLTF.preload("/Billboard.glb");
