/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Binder.glb -o /workspaces/windgapacademy/components/CityPackModels/Binder.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Binder.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Binder_Cube-Mesh"].geometry} material={materials.Binder_Blue} />
      <mesh geometry={nodes["Binder_Cube-Mesh_1"].geometry} material={materials.Sticker} />
      <mesh geometry={nodes["Binder_Cube-Mesh_2"].geometry} material={materials.Holder} />
      <mesh geometry={nodes["Binder_Cube-Mesh_3"].geometry} material={materials.Metal} />
    </group>
  );
}

useGLTF.preload("/Binder.glb");
