/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bird House.glb -o /workspaces/windgapacademy/components/CityPackModels/Bird House.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bird House.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BirdHouse1_1.geometry} material={materials.WoodBirdHouse1} />
      <mesh geometry={nodes.BirdHouse1_2.geometry} material={materials.WallBirdHouse1} />
      <mesh geometry={nodes.BirdHouse1_3.geometry} material={materials.RoofBirdHouse1} />
      <mesh geometry={nodes.BirdHouse1_4.geometry} material={materials.InsideBirdHouse1} />
    </group>
  )
}

useGLTF.preload('/Bird House.glb')
