/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Blank Picture Frame.glb -o /workspaces/windgapacademy/components/CityPackModels/Blank Picture Frame.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Blank Picture Frame.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat21} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat22} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat15} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat24} />
    </group>
  )
}

useGLTF.preload('/Blank Picture Frame.glb')
