/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Blender.glb -o /workspaces/windgapacademy/components/CityPackModels/Blender.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Blender.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Blender1.geometry}
        material={materials.MetalBlender1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[0.042, 0.293, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Pitcher1Blender1_1.geometry}
          material={materials.PlasticPitcher1Blender1}
        />
        <mesh
          geometry={nodes.Pitcher1Blender1_2.geometry}
          material={materials.Plastic2Pitcher1Blender1}
        />
      </group>
      <mesh
        geometry={nodes.Stayputlid1Blender1.geometry}
        material={materials.PlasticStayputlid1Blender1}
        position={[-0.001, 0.517, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.SteelBlade1Blender1.geometry}
        material={materials.DefaultMaterial}
        position={[-0.001, 0.198, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Button1Blender1.geometry}
        material={materials.MetalButton1Blender1}
        position={[0, 0.028, 0.131]}
        rotation={[-0.295, 0, 0]}
        scale={[3.649, 3.649, 0.362]}
      />
    </group>
  );
}

useGLTF.preload("/Blender.glb");
