/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bonsai.glb -o /workspaces/windgapacademy/components/CityPackModels/Bonsai.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bonsai.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bonsai1_1.geometry} material={materials.TrunkBonsai1} />
      <mesh geometry={nodes.Bonsai1_2.geometry} material={materials.LeafBonsai1} />
      <mesh geometry={nodes.Bonsai1_3.geometry} material={materials.VaseBonsai1} />
      <mesh geometry={nodes.Bonsai1_4.geometry} material={materials.GroundBonsai1} />
    </group>
  );
}

useGLTF.preload("/Bonsai.glb");
