/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bottle Musterd.glb -o /workspaces/windgapacademy/components/CityPackModels/Bottle Musterd.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bottle Musterd.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bottleMusterd.geometry} material={materials.yellow} />
    </group>
  );
}

useGLTF.preload("/Bottle Musterd.glb");
