/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bottle.glb -o /workspaces/windgapacademy/components/CityPackModels/Bottle.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bottle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bottle1.geometry} material={materials.Bottle1} />
    </group>
  )
}

useGLTF.preload('/Bottle.glb')
