/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bottle Ketchup.glb -o /workspaces/windgapacademy/components/CityPackModels/Bottle Ketchup.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bottle Ketchup.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bottleKetchup.geometry} material={materials.red} />
    </group>
  );
}

useGLTF.preload("/Bottle Ketchup.glb");
