/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bowl Broth.glb -o /workspaces/windgapacademy/components/CityPackModels/Bowl Broth.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bowl Broth.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bowlBroth_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.bowlBroth_1_1.geometry} material={materials.purple} />
      <mesh geometry={nodes.bowlBroth_1_2.geometry} material={materials.brown} />
      <mesh geometry={nodes.bowlBroth_1_3.geometry} material={materials.green} />
      <mesh geometry={nodes.bowlBroth_1_4.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.Group_2.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.Group_2_1.geometry} material={materials.yellow} />
      <mesh geometry={nodes.Group_3.geometry} material={materials.yellow} />
      <mesh geometry={nodes.Group_3_1.geometry} material={materials._defaultMat} />
    </group>
  );
}

useGLTF.preload("/Bowl Broth.glb");
