/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Boxing Gloves.glb -o /workspaces/windgapacademy/components/CityPackModels/Boxing Gloves.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Boxing Gloves.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.112, 0, -0.112]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
        <mesh
          geometry={nodes.RBoxingGloves1_1.geometry}
          material={materials.Lower1RBoxingGloves1}
        />
        <mesh
          geometry={nodes.RBoxingGloves1_2.geometry}
          material={materials.Upper1RBoxingGloves1}
        />
      </group>
      <group position={[0.112, 0, -0.112]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={-100}>
        <mesh
          geometry={nodes.LBoxingGloves1_1.geometry}
          material={materials.Lower1LBoxingGloves1}
        />
        <mesh
          geometry={nodes.LBoxingGloves1_2.geometry}
          material={materials.Upper1LBoxingGloves1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Boxing Gloves.glb");
