/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bread.glb -o /workspaces/windgapacademy/components/CityPackModels/Bread.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bread.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bread_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.bread_1_1.geometry} material={materials.brownLight} />
    </group>
  )
}

useGLTF.preload('/Bread.glb')
