/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Briefcase.glb -o /workspaces/windgapacademy/components/CityPackModels/Briefcase.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Briefcase.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box013.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box014.geometry} material={materials["03___Default"]} />
      <mesh geometry={nodes.Box015.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box016.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box018.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box019.geometry} material={materials["03___Default"]} />
      <mesh geometry={nodes.Box020.geometry} material={materials["03___Default"]} />
      <mesh geometry={nodes.Box021.geometry} material={materials["03___Default"]} />
      <mesh geometry={nodes.Box017_1.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box017_1_1.geometry} material={materials["02___Default"]} />
    </group>
  );
}

useGLTF.preload("/Briefcase.glb");
