/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Brown Building.glb -o /workspaces/windgapacademy/components/CityPackModels/Brown Building.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Brown Building.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.1, 1, -0.383]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.BrownBuilding_1.geometry} material={materials.brick_shade3} />
        <mesh geometry={nodes.BrownBuilding_2.geometry} material={materials.sandstone} />
        <mesh geometry={nodes.BrownBuilding_3.geometry} material={materials.window_glass} />
        <mesh geometry={nodes.BrownBuilding_4.geometry} material={materials.window_frame} />
        <mesh geometry={nodes.BrownBuilding_5.geometry} material={materials.concrete} />
      </group>
    </group>
  );
}

useGLTF.preload("/Brown Building.glb");
