/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Building Red Corner.glb -o /workspaces/windgapacademy/components/CityPackModels/Building Red Corner.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Building Red Corner.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.516, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={60}>
        <mesh geometry={nodes.BuildingCornerRed_1.geometry} material={materials.brick_shade1} />
        <mesh geometry={nodes.BuildingCornerRed_2.geometry} material={materials.concrete} />
        <mesh geometry={nodes.BuildingCornerRed_3.geometry} material={materials.window_frame} />
        <mesh geometry={nodes.BuildingCornerRed_4.geometry} material={materials.window_glass} />
        <mesh geometry={nodes.BuildingCornerRed_5.geometry} material={materials.wood} />
        <mesh geometry={nodes.BuildingCornerRed_6.geometry} material={materials.sandstone} />
        <mesh geometry={nodes.BuildingCornerRed_7.geometry} material={materials.brick_shade2} />
      </group>
    </group>
  );
}

useGLTF.preload("/Building Red Corner.glb");
