/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Building Red.glb -o /workspaces/windgapacademy/components/CityPackModels/Building Red.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Building Red.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.112, 1.665, 0.554]} rotation={[-Math.PI / 2, 0, 0]} scale={60}>
        <mesh geometry={nodes.BuildingRed1_1.geometry} material={materials.window_frame} />
        <mesh geometry={nodes.BuildingRed1_2.geometry} material={materials.brick_shade1} />
        <mesh geometry={nodes.BuildingRed1_3.geometry} material={materials.window_glass} />
        <mesh geometry={nodes.BuildingRed1_4.geometry} material={materials.sandstone} />
        <mesh geometry={nodes.BuildingRed1_5.geometry} material={materials.brick_shade2} />
        <mesh geometry={nodes.BuildingRed1_6.geometry} material={materials.concrete} />
        <mesh geometry={nodes.BuildingRed1_7.geometry} material={materials.wood} />
      </group>
    </group>
  );
}

useGLTF.preload("/Building Red.glb");
