/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bunk Bed.glb -o /workspaces/windgapacademy/components/CityPackModels/Bunk Bed.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bunk Bed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.BunkBed1_1.geometry} material={materials.MattressBundBed1} />
        <mesh geometry={nodes.BunkBed1_2.geometry} material={materials.PillowsBunkBed1} />
        <mesh geometry={nodes.BunkBed1_3.geometry} material={materials.Wood1BunkBed1_BunkBed1} />
      </group>
      <group position={[0.342, -0.106, 1.222]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer1_BunkBed1_1.geometry} material={materials.Wood1Drawer1_BunkBed1} />
        <mesh geometry={nodes.Drawer1_BunkBed1_2.geometry} material={materials.Metal1Drawer1_BunkBed1} />
      </group>
      <group position={[0.214, -0.488, 1.233]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer2_BunkBed1_1.geometry} material={materials.Wood1Drawer2_BunkBed1} />
        <mesh geometry={nodes.Drawer2_BunkBed1_2.geometry} material={materials.Metal1Drawer2_BunkBed1} />
      </group>
      <group position={[0.086, -0.857, 1.236]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer3_BunkBed1_1.geometry} material={materials.Wood1Drawer3_BunkBed1} />
        <mesh geometry={nodes.Drawer3_BunkBed1_2.geometry} material={materials.Metal1Drawer3_BunkBed1} />
      </group>
      <group position={[-0.043, -1.248, 1.244]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer4_BunkBed1_1.geometry} material={materials.Wood1Drawer4_BunkBed1} />
        <mesh geometry={nodes.Drawer4_BunkBed1_2.geometry} material={materials.Metal1Drawer4_BunkBed1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bunk Bed.glb')
