/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Burger Cheese.glb -o /workspaces/windgapacademy/components/CityPackModels/Burger Cheese.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Burger Cheese.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bunBottom.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.bunTop.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.cheese.geometry} material={materials.yellow} />
      <mesh geometry={nodes.patty.geometry} material={materials.brownDark} />
    </group>
  );
}

useGLTF.preload("/Burger Cheese.glb");
