/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bus stop sign.glb -o /workspaces/windgapacademy/components/CityPackModels/Bus stop sign.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Bus stop sign.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Bussy_1.geometry} material={materials.Orang} />
        <mesh geometry={nodes.Bussy_2.geometry} material={materials.White} />
        <mesh geometry={nodes.Bussy_3.geometry} material={materials.Black} />
        <mesh geometry={nodes.Bussy_4.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Bussy_5.geometry} material={materials.Silver} />
      </group>
    </group>
  );
}

useGLTF.preload("/Bus stop sign.glb");
