/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Bush with Flowers.glb -o /workspaces/windgapacademy/components/CityPackModels/Bush with Flowers.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bush with Flowers.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bush_Common_Flowers_1.geometry} material={materials.Leaves_NormalTree} />
      <mesh geometry={nodes.Bush_Common_Flowers_2.geometry} material={materials.Flowers} />
    </group>
  )
}

useGLTF.preload('/Bush with Flowers.glb')
