/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cabbage.glb -o /workspaces/windgapacademy/components/CityPackModels/Cabbage.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Cabbage.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cabbage_1.geometry} material={materials.green} />
      <mesh geometry={nodes.cabbage_1_1.geometry} material={materials._defaultMat} />
    </group>
  );
}

useGLTF.preload("/Cabbage.glb");
