/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cake Slicer.glb -o /workspaces/windgapacademy/components/CityPackModels/Cake Slicer.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Cake Slicer.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cakeSlicer_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.cakeSlicer_1_1.geometry} material={materials.white} />
    </group>
  );
}

useGLTF.preload("/Cake Slicer.glb");
