/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cake.glb -o /workspaces/windgapacademy/components/CityPackModels/Cake.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cake.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.slice_6.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice_6_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.slice_6_2.geometry} material={materials.red} />
      <mesh geometry={nodes.slice_6_3.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.slice_6_4.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.slice_6_5.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.slice_7.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.slice_7_1.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice_7_2.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.slice_7_3.geometry} material={materials.red} />
      <mesh geometry={nodes.slice_7_4.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.slice_7_5.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.slice_8.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.slice_8_1.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice_8_2.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.slice_8_3.geometry} material={materials.red} />
      <mesh geometry={nodes.slice_8_4.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.slice_8_5.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.slice_9.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.slice_9_1.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice_9_2.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.slice_9_3.geometry} material={materials.red} />
      <mesh geometry={nodes.slice_9_4.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.slice_9_5.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.slice_10.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.slice_10_1.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice_10_2.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.slice_10_3.geometry} material={materials.red} />
      <mesh geometry={nodes.slice_10_4.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.slice_10_5.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.slice_11.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.slice_11_1.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice_11_2.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.slice_11_3.geometry} material={materials.red} />
      <mesh geometry={nodes.slice_11_4.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.slice_11_5.geometry} material={materials.purpleLight} />
    </group>
  )
}

useGLTF.preload('/Cake.glb')
