/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Calendar.glb -o /workspaces/windgapacademy/components/CityPackModels/Calendar.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Calendar.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Calender_01_Plane003_1.geometry} material={materials.FFFFFF} />
      <mesh geometry={nodes.Calender_01_Plane003_1_1.geometry} material={materials['1A1A1A']} />
      <mesh geometry={nodes.Calender_01_Plane003_1_2.geometry} material={materials['00BCD4']} />
      <mesh geometry={nodes.Calender_01_Plane003_1_3.geometry} material={materials['455A64']} />
    </group>
  )
}

useGLTF.preload('/Calendar.glb')
