/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Calendar-8GqQAqxi3qk.glb -o /workspaces/windgapacademy/components/CityPackModels/Calendar-8GqQAqxi3qk.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Calendar-8GqQAqxi3qk.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh1_Calendar_C03_1_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh3_Calendar_C03_2_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh4_Calendar_C03_3_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh6_Calendar_C03_4_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh7_Calendar_C03_5_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh8_Calendar_C03_6_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh9_Calendar_C03_7_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh10_Calendar_C03_8_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh11_Calendar_C03_9_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh12_Calendar_C03_10_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh13_Calendar_C03_11_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh14_Calendar_C03_12_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh15_Calendar_C03_13_Calendar_LowPoly1_Model.geometry}
        material={materials.Calendar_Aquamarine}
      />
      <mesh
        geometry={nodes.Mesh2_Calendar_C01_1_Calendar_LowPoly1_Model_1.geometry}
        material={materials.Calendar_Ivory}
      />
      <mesh
        geometry={nodes.Mesh2_Calendar_C01_1_Calendar_LowPoly1_Model_1_1.geometry}
        material={materials.Calendar_Texture}
      />
      <mesh
        geometry={nodes.Mesh2_Calendar_C01_1_Calendar_LowPoly1_Model_1_2.geometry}
        material={materials.FrontColor}
      />
      <mesh
        geometry={nodes.Mesh5_Calendar_C02_1_Calendar_LowPoly1_Model_1.geometry}
        material={materials.Calendar_Ivory}
      />
      <mesh
        geometry={nodes.Mesh5_Calendar_C02_1_Calendar_LowPoly1_Model_1_1.geometry}
        material={materials.FrontColor}
      />
    </group>
  );
}

useGLTF.preload("/Calendar-8GqQAqxi3qk.glb");
