/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Can Fridge.glb -o /workspaces/windgapacademy/components/CityPackModels/Can Fridge.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Can Fridge.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Environment_CanFridge.geometry} material={materials.Atlas} />
      <mesh geometry={nodes.Environment_CanFridge_Door_Environment_CanFridge_Door_Atlas.geometry} material={materials.Atlas} />
      <mesh geometry={nodes.Environment_CanFridge_Door_Environment_CanFridge_Door_Glass.geometry} material={materials.Glass} />
    </group>
  )
}

useGLTF.preload('/Can Fridge.glb')
