/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Can Small.glb -o /workspaces/windgapacademy/components/CityPackModels/Can Small.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Can Small.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.canSmall_1.geometry} material={materials.greyLight} />
      <mesh geometry={nodes.canSmall_1_1.geometry} material={materials.purple} />
      <mesh geometry={nodes.canSmall_1_2.geometry} material={materials.greyDark} />
    </group>
  );
}

useGLTF.preload("/Can Small.glb");
