/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Can.glb -o /workspaces/windgapacademy/components/CityPackModels/Can.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Can.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.can_1.geometry} material={materials.greyLight} />
      <mesh geometry={nodes.can_1_1.geometry} material={materials.red} />
      <mesh geometry={nodes.can_1_2.geometry} material={materials.greyDark} />
    </group>
  );
}

useGLTF.preload("/Can.glb");
