/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Capsicum.glb -o /workspaces/windgapacademy/components/CityPackModels/Capsicum.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Capsicum.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.paprika_1.geometry} material={materials.red} />
      <mesh geometry={nodes.paprika_1_1.geometry} material={materials.green} />
    </group>
  );
}

useGLTF.preload("/Capsicum.glb");
