/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Car-unqqkULtRU.glb -o /workspaces/windgapacademy/components/CityPackModels/Car-unqqkULtRU.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Car-unqqkULtRU.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["NormalCar2_Cube002-Mesh"].geometry} material={materials.LightBlue} />
      <mesh geometry={nodes["NormalCar2_Cube002-Mesh_1"].geometry} material={materials.Windows} />
      <mesh geometry={nodes["NormalCar2_Cube002-Mesh_2"].geometry} material={materials.Black} />
      <mesh geometry={nodes["NormalCar2_Cube002-Mesh_3"].geometry} material={materials.Grey} />
      <mesh
        geometry={nodes["NormalCar2_Cube002-Mesh_4"].geometry}
        material={materials.Headlights}
      />
      <mesh
        geometry={nodes["NormalCar2_Cube002-Mesh_5"].geometry}
        material={materials["Material.007"]}
      />
      <mesh
        geometry={nodes["NormalCar2_Cube002-Mesh_6"].geometry}
        material={materials.TailLights}
      />
      <mesh
        geometry={nodes["NormalCar2_BackWheels_Cylinder003-Mesh"].geometry}
        material={materials.Black}
      />
      <mesh
        geometry={nodes["NormalCar2_BackWheels_Cylinder003-Mesh_1"].geometry}
        material={materials.Grey}
      />
      <mesh
        geometry={nodes["NormalCar2_FrontLeftWheel_Cylinder015-Mesh"].geometry}
        material={materials.Grey}
      />
      <mesh
        geometry={nodes["NormalCar2_FrontLeftWheel_Cylinder015-Mesh_1"].geometry}
        material={materials.Black}
      />
      <mesh
        geometry={nodes["NormalCar2_FrontRightWheel_Cylinder016-Mesh"].geometry}
        material={materials.Grey}
      />
      <mesh
        geometry={nodes["NormalCar2_FrontRightWheel_Cylinder016-Mesh_1"].geometry}
        material={materials.Black}
      />
    </group>
  );
}

useGLTF.preload("/Car-unqqkULtRU.glb");
