/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Car.glb -o /workspaces/windgapacademy/components/CityPackModels/Car.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Car.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["NormalCar1_Cube012-Mesh"].geometry} material={materials.Blue} />
      <mesh geometry={nodes["NormalCar1_Cube012-Mesh_1"].geometry} material={materials.Windows} />
      <mesh geometry={nodes["NormalCar1_Cube012-Mesh_2"].geometry} material={materials.Black} />
      <mesh geometry={nodes["NormalCar1_Cube012-Mesh_3"].geometry} material={materials.Grey} />
      <mesh
        geometry={nodes["NormalCar1_Cube012-Mesh_4"].geometry}
        material={materials.Headlights}
      />
      <mesh
        geometry={nodes["NormalCar1_Cube012-Mesh_5"].geometry}
        material={materials.TailLights}
      />
      <mesh
        geometry={nodes["NormalCar1_BackWheels_Cube011-Mesh"].geometry}
        material={materials.Black}
      />
      <mesh
        geometry={nodes["NormalCar1_BackWheels_Cube011-Mesh_1"].geometry}
        material={materials.Grey}
      />
      <mesh
        geometry={nodes["NormalCar1_FrontLeftWheel_Cube007-Mesh"].geometry}
        material={materials.Grey}
      />
      <mesh
        geometry={nodes["NormalCar1_FrontLeftWheel_Cube007-Mesh_1"].geometry}
        material={materials.Black}
      />
      <mesh
        geometry={nodes["NormalCar1_FrontRightWheel_Cube008-Mesh"].geometry}
        material={materials.Grey}
      />
      <mesh
        geometry={nodes["NormalCar1_FrontRightWheel_Cube008-Mesh_1"].geometry}
        material={materials.Black}
      />
    </group>
  );
}

useGLTF.preload("/Car.glb");
