/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cardboard Boxes-pMdXdrUHvX.glb -o /workspaces/windgapacademy/components/CityPackModels/Cardboard Boxes-pMdXdrUHvX.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Cardboard Boxes-pMdXdrUHvX.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={100}>
        <mesh geometry={nodes.Cardboard_Boxes_1.geometry} material={materials.mat20} />
        <mesh geometry={nodes.Cardboard_Boxes_2.geometry} material={materials.mat19} />
      </group>
    </group>
  );
}

useGLTF.preload("/Cardboard Boxes-pMdXdrUHvX.glb");
