/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cardboard Boxes.glb -o /workspaces/windgapacademy/components/CityPackModels/Cardboard Boxes.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cardboard Boxes.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={36.327}>
        <mesh geometry={nodes.CardboardBoxes_4_1.geometry} material={materials.Cardboard} />
        <mesh geometry={nodes.CardboardBoxes_4_2.geometry} material={materials.Tape} />
      </group>
    </group>
  )
}

useGLTF.preload('/Cardboard Boxes.glb')
