/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Carton Small.glb -o /workspaces/windgapacademy/components/CityPackModels/Carton Small.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Carton Small.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cartonSmall_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.cartonSmall_1_1.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.cartonSmall_1_2.geometry} material={materials.white} />
    </group>
  );
}

useGLTF.preload("/Carton Small.glb");
