/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cash register.glb -o /workspaces/windgapacademy/components/CityPackModels/Cash register.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Cash register.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CashRegister_mesh.geometry} material={materials.CashRegister_mat} />
    </group>
  );
}

useGLTF.preload("/Cash register.glb");
