/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Castle.glb -o /workspaces/windgapacademy/components/CityPackModels/Castle.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Castle.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Castle.geometry} material={materials.Diffuse_color} scale={100} />
    </group>
  );
}

useGLTF.preload("/Castle.glb");
