/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cauliflower.glb -o /workspaces/windgapacademy/components/CityPackModels/Cauliflower.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Cauliflower.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cauliflower_1.geometry} material={materials.green} />
      <mesh geometry={nodes.cauliflower_1_1.geometry} material={materials._defaultMat} />
    </group>
  );
}

useGLTF.preload("/Cauliflower.glb");
