/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/CCTV Camera.glb -o /workspaces/windgapacademy/components/CityPackModels/CCTV Camera.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/CCTV Camera.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere007.geometry} material={materials["Material.004"]} />
      <mesh
        geometry={nodes.Cylinder015_Cylinder021.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Cylinder014_Cylinder020.geometry}
        material={materials["Material.002"]}
      />
      <mesh geometry={nodes.Cylinder_Cylinder009.geometry} material={materials["Material.003"]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cylinder000_Cylinder002.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cylinder002_Cylinder004.geometry} material={materials.Material} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials.Material} />
      <mesh
        geometry={nodes.Cylinder001_Cylinder010.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Cylinder005_Cylinder011.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Cylinder006_Cylinder012.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Cylinder007_Cylinder013.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Cylinder008_Cylinder014.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Cylinder009_Cylinder015.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Cylinder010_Cylinder016.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Cylinder011_Cylinder017.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Cylinder012_Cylinder018.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Cylinder013_Cylinder019.geometry}
        material={materials["Material.003"]}
      />
      <mesh geometry={nodes.Cylinder016_Cylinder000.geometry} material={materials.Material} />
    </group>
  );
}

useGLTF.preload("/CCTV Camera.glb");
