/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Ceiling Lamp-Tz2NayqjsK.glb -o /workspaces/windgapacademy/components/CityPackModels/Ceiling Lamp-Tz2NayqjsK.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Ceiling Lamp-Tz2NayqjsK.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.CeilingLamp3_1.geometry} material={materials.MetalCeilingLamp3} />
        <mesh geometry={nodes.CeilingLamp3_2.geometry} material={materials.LightCeilingLamp3} />
      </group>
    </group>
  );
}

useGLTF.preload("/Ceiling Lamp-Tz2NayqjsK.glb");
