/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Ceiling Lamp-OTJPOdps4p.glb -o /workspaces/windgapacademy/components/CityPackModels/Ceiling Lamp-OTJPOdps4p.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Ceiling Lamp-OTJPOdps4p.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.CeilingLamp2_1.geometry} material={materials.Metal1CeilingLamp2} />
        <mesh geometry={nodes.CeilingLamp2_2.geometry} material={materials.Lamp1CeilingLamp2} />
      </group>
    </group>
  );
}

useGLTF.preload("/Ceiling Lamp-OTJPOdps4p.glb");
