/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Chair.glb -o /workspaces/windgapacademy/components/CityPackModels/Chair.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Chair.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chair1_1.geometry} material={materials.PadChair1} />
      <mesh geometry={nodes.Chair1_2.geometry} material={materials.Pad2Chair1} />
      <mesh geometry={nodes.Chair1_3.geometry} material={materials.Chair1} />
    </group>
  )
}

useGLTF.preload('/Chair.glb')
