/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cheese Slicer.glb -o /workspaces/windgapacademy/components/CityPackModels/Cheese Slicer.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Cheese Slicer.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cheeseSlicer_1.geometry} material={materials.greyDark} />
      <mesh geometry={nodes.cheeseSlicer_1_1.geometry} material={materials.white} />
    </group>
  );
}

useGLTF.preload("/Cheese Slicer.glb");
