/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cherries.glb -o /workspaces/windgapacademy/components/CityPackModels/Cherries.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cherries.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cherries_1.geometry} material={materials.green} />
      <mesh geometry={nodes.cherries_1_1.geometry} material={materials.red} />
      <mesh geometry={nodes.cherries_1_2.geometry} material={materials.brown} />
    </group>
  )
}

useGLTF.preload('/Cherries.glb')
