/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Chiminea.glb -o /workspaces/windgapacademy/components/CityPackModels/Chiminea.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Chiminea.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chiminea1_1.geometry} material={materials.MetalChiminea1} />
      <mesh geometry={nodes.Chiminea1_2.geometry} material={materials.Chiminea1} />
      <mesh geometry={nodes.Chiminea1_3.geometry} material={materials.InsideChiminea1} />
    </group>
  );
}

useGLTF.preload("/Chiminea.glb");
