/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Chinese.glb -o /workspaces/windgapacademy/components/CityPackModels/Chinese.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Chinese.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.chopstick.geometry} material={materials.brown} />
      <mesh geometry={nodes.chopstick_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.chinese_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.chinese_1_1.geometry} material={materials.white} />
      <mesh geometry={nodes.chinese_1_2.geometry} material={materials.red} />
      <mesh geometry={nodes.chinese_1_3.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('/Chinese.glb')
