/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Chopstick Fancy.glb -o /workspaces/windgapacademy/components/CityPackModels/Chopstick Fancy.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Chopstick Fancy.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.chopstickFancy_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.chopstickFancy_1_1.geometry} material={materials.red} />
      <mesh geometry={nodes.chopstickFancy_1_2.geometry} material={materials.brownLight} />
    </group>
  );
}

useGLTF.preload("/Chopstick Fancy.glb");
