/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Church.glb -o /workspaces/windgapacademy/components/CityPackModels/Church.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Church.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Church.geometry} material={materials.Diffuse_color} scale={100} />
    </group>
  );
}

useGLTF.preload("/Church.glb");
