/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/clipboard.glb -o /workspaces/windgapacademy/components/CityPackModels/clipboard.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/clipboard.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Node-Mesh"].geometry} material={materials.mat20} />
      <mesh geometry={nodes["Node-Mesh_1"].geometry} material={materials.mat21} />
      <mesh geometry={nodes["Node-Mesh_2"].geometry} material={materials.mat22} />
    </group>
  );
}

useGLTF.preload("/clipboard.glb");
