/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Clover-u5SOgBFiut.glb -o /workspaces/windgapacademy/components/CityPackModels/Clover-u5SOgBFiut.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Clover-u5SOgBFiut.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Clover_2.geometry} material={materials.Leaves} />
    </group>
  );
}

useGLTF.preload("/Clover-u5SOgBFiut.glb");
