/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Coat rack.glb -o /workspaces/windgapacademy/components/CityPackModels/Coat rack.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Coat rack.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Coat_rack_01_Circle006.geometry} material={materials["1A1A1A"]} />
    </group>
  );
}

useGLTF.preload("/Coat rack.glb");
