/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Coat Rack.glb -o /workspaces/windgapacademy/components/CityPackModels/Coat Rack.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Coat Rack.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.coatRack_2.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.coatRack_2_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.coatRack_3.geometry} material={materials.wood} />
      <mesh geometry={nodes.coatRack_3_1.geometry} material={materials.metalMedium} />
    </group>
  )
}

useGLTF.preload('/Coat Rack.glb')
