/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cocktail.glb -o /workspaces/windgapacademy/components/CityPackModels/Cocktail.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Cocktail.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.straw.geometry} material={materials.green} />
      <mesh geometry={nodes.cocktail_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.cocktail_1_1.geometry} material={materials.greyLight} />
      <mesh geometry={nodes.cocktail_1_2.geometry} material={materials.red} />
      <mesh geometry={nodes.lemon_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.lemon_1_1.geometry} material={materials.yellow} />
    </group>
  );
}

useGLTF.preload("/Cocktail.glb");
