/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Coconut Half.glb -o /workspaces/windgapacademy/components/CityPackModels/Coconut Half.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Coconut Half.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.coconutHalf_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.coconutHalf_1_1.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/Coconut Half.glb')
