/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Coffee Cup.glb -o /workspaces/windgapacademy/components/CityPackModels/Coffee Cup.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Coffee Cup.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.CoffeeCup1.geometry}
        material={materials.PorcelainCoffeCup1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Coffee Cup.glb");
