/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Coffee Pot.glb -o /workspaces/windgapacademy/components/CityPackModels/Coffee Pot.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Coffee Pot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1544541267.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group795075715.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1522714784.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1418641120.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group9310328.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1485131688.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1416553862.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group1335962337.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group698028249.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group2097960826.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group734777039.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh303977725.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh303977725_1.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh303977725_2.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh303977725_3.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh303977725_4.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh303977725_5.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh303977725_6.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh303977725_7.geometry} material={materials.mat10} />
    </group>
  )
}

useGLTF.preload('/Coffee Pot.glb')
