/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Coffee Table.glb -o /workspaces/windgapacademy/components/CityPackModels/Coffee Table.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Coffee Table.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tableCoffee.geometry} material={materials.wood} />
      <mesh geometry={nodes.tableCoffee_1.geometry} material={materials.wood} />
    </group>
  );
}

useGLTF.preload("/Coffee Table.glb");
