/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Coffee Machine.glb -o /workspaces/windgapacademy/components/CityPackModels/Coffee Machine.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Coffee Machine.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.FilterHolder1CoffeeMachine1.geometry}
        material={materials.SteelFilterHolder1CoffeeMachine1}
        position={[0.014, -0.003, -0.002]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.SteamPipe1CoffeeMachine1.geometry}
        material={materials.SteelPipe1CoffeMachine1}
        position={[-0.199, 0.002, 0.068]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.CoffeeMachine1_1.geometry} material={materials.SteelCoffeMachine1} />
        <mesh geometry={nodes.CoffeeMachine1_2.geometry} material={materials.MetalCoffeMachine1} />
      </group>
      <mesh
        geometry={nodes.SteamKnob1CoffeeMachine1.geometry}
        material={materials.SteelSteamKnob1CoffeeMachine1}
        position={[-0.309, 0.293, 0.028]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Coffee Machine.glb");
