/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Computer Screen.glb -o /workspaces/windgapacademy/components/CityPackModels/Computer Screen.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Computer Screen.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.computerScreen_2.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.computerScreen_2_1.geometry} material={materials.metal} />
      <mesh geometry={nodes.computerScreen_3.geometry} material={materials.metal} />
      <mesh geometry={nodes.computerScreen_3_1.geometry} material={materials.metalDark} />
    </group>
  );
}

useGLTF.preload("/Computer Screen.glb");
