/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Computer mouse.glb -o /workspaces/windgapacademy/components/CityPackModels/Computer mouse.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Computer mouse.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ComputerMouse_mesh.geometry} material={materials.ComputerMouse_mat1} />
    </group>
  )
}

useGLTF.preload('/Computer mouse.glb')
