/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cooking Fork.glb -o /workspaces/windgapacademy/components/CityPackModels/Cooking Fork.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Cooking Fork.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cookingFork_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.cookingFork_1_1.geometry} material={materials.white} />
    </group>
  );
}

useGLTF.preload("/Cooking Fork.glb");
