/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cookie Chocolate.glb -o /workspaces/windgapacademy/components/CityPackModels/Cookie Chocolate.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Cookie Chocolate.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cookieChocolate_1.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.cookieChocolate_1_1.geometry} material={materials._defaultMat} />
    </group>
  );
}

useGLTF.preload("/Cookie Chocolate.glb");
