/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cooking Spatula.glb -o /workspaces/windgapacademy/components/CityPackModels/Cooking Spatula.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cooking Spatula.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cookingSpatula_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.cookingSpatula_1_1.geometry} material={materials.white} />
    </group>
  )
}

useGLTF.preload('/Cooking Spatula.glb')
