/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cooking Knife Chopping.glb -o /workspaces/windgapacademy/components/CityPackModels/Cooking Knife Chopping.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cooking Knife Chopping.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cookingKnifeChopping_1.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.cookingKnifeChopping_1_1.geometry} material={materials.greyLight} />
      <mesh geometry={nodes.cookingKnifeChopping_1_2.geometry} material={materials.white} />
    </group>
  )
}

useGLTF.preload('/Cooking Knife Chopping.glb')
