/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Corn.glb -o /workspaces/windgapacademy/components/CityPackModels/Corn.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Corn.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.corn_1.geometry} material={materials.green} />
      <mesh geometry={nodes.corn_1_1.geometry} material={materials.yellow} />
    </group>
  );
}

useGLTF.preload("/Corn.glb");
