/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Corn Dog.glb -o /workspaces/windgapacademy/components/CityPackModels/Corn Dog.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Corn Dog.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cornDog.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.dog.geometry} material={materials.brownDark} />
    </group>
  )
}

useGLTF.preload('/Corn Dog.glb')
