/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Couch Small.glb -o /workspaces/windgapacademy/components/CityPackModels/Couch Small.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Couch Small.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Couch_Small1_1.geometry} material={materials.Couch_Blue} />
        <mesh geometry={nodes.Couch_Small1_2.geometry} material={materials.Black} />
      </group>
    </group>
  );
}

useGLTF.preload("/Couch Small.glb");
