/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Couch | Wide.glb -o /workspaces/windgapacademy/components/CityPackModels/Couch | Wide.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Couch | Wide.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Node-Mesh"].geometry} material={materials.mat23} />
      <mesh geometry={nodes["Node-Mesh_1"].geometry} material={materials.mat17} />
      <mesh geometry={nodes["Node-Mesh_2"].geometry} material={materials.mat16} />
      <mesh geometry={nodes["Node-Mesh_3"].geometry} material={materials.mat20} />
    </group>
  );
}

useGLTF.preload("/Couch | Wide.glb");
