/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Crushed Soda Can.glb -o /workspaces/windgapacademy/components/CityPackModels/Crushed Soda Can.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Crushed Soda Can.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Cylinder-Mesh'].geometry} material={materials.Red_Metal} />
      <mesh geometry={nodes['Cylinder-Mesh_1'].geometry} material={materials.Metal} />
    </group>
  )
}

useGLTF.preload('/Crushed Soda Can.glb')
