/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cup Tea.glb -o /workspaces/windgapacademy/components/CityPackModels/Cup Tea.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cup Tea.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cupThea_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.cupThea_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.cupThea_1_2.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.label_1.geometry} material={materials.green} />
      <mesh geometry={nodes.label_1_1.geometry} material={materials.brown} />
    </group>
  )
}

useGLTF.preload('/Cup Tea.glb')
