/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cup of tea.glb -o /workspaces/windgapacademy/components/CityPackModels/Cup of tea.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cup of tea.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.lambert6SG} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.lambert7SG} />
    </group>
  )
}

useGLTF.preload('/Cup of tea.glb')
