/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cupcake.glb -o /workspaces/windgapacademy/components/CityPackModels/Cupcake.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Cupcake.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Cupcake_1.geometry} material={materials.LightYellow} />
        <mesh geometry={nodes.Cupcake_2.geometry} material={materials.Pink} />
        <mesh geometry={nodes.Cupcake_3.geometry} material={materials.DarkBrown} />
      </group>
    </group>
  );
}

useGLTF.preload("/Cupcake.glb");
