/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Curtains Double.glb -o /workspaces/windgapacademy/components/CityPackModels/Curtains Double.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Curtains Double.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Curtains_Double_1.geometry} material={materials.LightMetal} />
        <mesh geometry={nodes.Curtains_Double_2.geometry} material={materials.Couch_Blue} />
      </group>
    </group>
  );
}

useGLTF.preload("/Curtains Double.glb");
