/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Cutting Board.glb -o /workspaces/windgapacademy/components/CityPackModels/Cutting Board.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Cutting Board.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cuttingBoard_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.cuttingBoard_1_1.geometry} material={materials.brown} />
    </group>
  );
}

useGLTF.preload("/Cutting Board.glb");
