/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Darts.glb -o /workspaces/windgapacademy/components/CityPackModels/Darts.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Darts.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat19} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat15} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat12} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat8} />
      <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat22} />
    </group>
  )
}

useGLTF.preload('/Darts.glb')
