/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Dead Tree-CD4edbPSGm.glb -o /workspaces/windgapacademy/components/CityPackModels/Dead Tree-CD4edbPSGm.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Dead Tree-CD4edbPSGm.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DeadTree_5.geometry} material={materials.Bark_DeadTree} />
    </group>
  );
}

useGLTF.preload("/Dead Tree-CD4edbPSGm.glb");
