/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Dead Tree-n8FhMgMldD.glb -o /workspaces/windgapacademy/components/CityPackModels/Dead Tree-n8FhMgMldD.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Dead Tree-n8FhMgMldD.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DeadTree_4.geometry} material={materials.Bark_DeadTree} />
    </group>
  )
}

useGLTF.preload('/Dead Tree-n8FhMgMldD.glb')
