/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Dead Tree-Mcd2zYqyww.glb -o /workspaces/windgapacademy/components/CityPackModels/Dead Tree-Mcd2zYqyww.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Dead Tree-Mcd2zYqyww.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DeadTree_2.geometry} material={materials.Bark_DeadTree} />
    </group>
  )
}

useGLTF.preload('/Dead Tree-Mcd2zYqyww.glb')
