/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Debris Papers.glb -o /workspaces/windgapacademy/components/CityPackModels/Debris Papers.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Debris Papers.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Debris_Papers_2.geometry} material={materials.White} rotation={[-Math.PI / 2, 0, 0.308]} scale={11.411} />
    </group>
  )
}

useGLTF.preload('/Debris Papers.glb')
