/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Desk.glb -o /workspaces/windgapacademy/components/CityPackModels/Desk.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Desk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Desk.geometry} material={materials.Material} scale={100} />
    </group>
  )
}

useGLTF.preload('/Desk.glb')
