/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Desk-7ban171PzCS.glb -o /workspaces/windgapacademy/components/CityPackModels/Desk-7ban171PzCS.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Desk-7ban171PzCS.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials._5_Drawer} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials._5_Drawer_1} />
    </group>
  )
}

useGLTF.preload('/Desk-7ban171PzCS.glb')
