/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Desk-EtJlOllzbf.glb -o /workspaces/windgapacademy/components/CityPackModels/Desk-EtJlOllzbf.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Desk-EtJlOllzbf.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.383, 0.67, 0.306]} rotation={[-Math.PI / 2, 0, 1.643]} scale={3.082}>
        <mesh geometry={nodes.Chair_1.geometry} material={materials['Executive.003']} />
        <mesh geometry={nodes.Chair_2.geometry} material={materials['Executive__1.003']} />
        <mesh geometry={nodes.Chair_3.geometry} material={materials['Executive__2.003']} />
        <mesh geometry={nodes.Chair_4.geometry} material={materials['Executive__3.003']} />
      </group>
      <group position={[-0.778, 0.916, 0.419]} rotation={[-Math.PI, 1.571, 0]} scale={[10000, 9999.998, 9999.998]}>
        <mesh geometry={nodes['Desk-V86Go2rlnq_1'].geometry} material={materials['DarkWood.012']} />
        <mesh geometry={nodes['Desk-V86Go2rlnq_2'].geometry} material={materials['Wood.013']} />
      </group>
      <group position={[-0.135, 1.162, -0.245]} rotation={[-Math.PI / 2, 0, 2.301]} scale={[8561.474, 8561.474, 8561.471]}>
        <mesh geometry={nodes.Light_Desk_1.geometry} material={materials['Black.097']} />
        <mesh geometry={nodes.Light_Desk_2.geometry} material={materials['LightMetal.027']} />
        <mesh geometry={nodes.Light_Desk_3.geometry} material={materials['White.053']} />
      </group>
      <group position={[-0.111, 0.919, 0.472]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={154.397}>
        <mesh geometry={nodes.Computer_Screen_1.geometry} material={materials.metalDark} />
        <mesh geometry={nodes.Computer_Screen_2.geometry} material={materials['metal.002']} />
      </group>
      <mesh geometry={nodes['Keyboard-aPwr5p1dluw'].geometry} material={materials['Mat.065']} position={[-0.552, 0.919, 0.416]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.625} />
      <mesh geometry={nodes.Mousepad002.geometry} material={materials['Mousepad.001']} position={[-0.561, 0.919, 0.771]} scale={[1175.398, 15.54, 1430.879]} />
      <mesh geometry={nodes.Computer_mouse.geometry} material={materials.ComputerMouse_mat1} position={[-0.566, 0.92, 0.91]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.93} />
      <group position={[-0.111, 0.945, 1.079]} rotation={[-Math.PI / 2, 0, 3.106]} scale={[6.489, 9.4, 0.204]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-0.328, 0.973, -0.086]} rotation={[Math.PI, 1.424, 0]} scale={626.776}>
        <mesh geometry={nodes.Office_Phone002_1.geometry} material={materials['Light grey']} />
        <mesh geometry={nodes.Office_Phone002_2.geometry} material={materials['Grey Plastic']} />
        <mesh geometry={nodes.Office_Phone002_3.geometry} material={materials.Screen} />
        <mesh geometry={nodes.Office_Phone002_4.geometry} material={materials['Dark Grey Plastic']} />
      </group>
      <group position={[-0.556, 0.009, -0.604]} rotation={[-1.407, 0, Math.PI]} scale={0}>
        <mesh geometry={nodes.Laptop_bag_1.geometry} material={materials['02___Default.049']} />
        <mesh geometry={nodes.Laptop_bag_2.geometry} material={materials['03___Default.025']} />
        <mesh geometry={nodes.Laptop_bag_3.geometry} material={materials['_crayfishdiffuse.049']} />
        <mesh geometry={nodes.Laptop_bag_4.geometry} material={materials['_crayfishdiffuse-2.012']} />
      </group>
      <group position={[-0.094, 1.409, 0.484]} rotation={[0, -Math.PI / 2, 0]} scale={6.449}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Grey.002']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Dark} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-0.4, 0.244, -0.257]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.162}>
        <mesh geometry={nodes.System_unit001_1.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.System_unit001_2.geometry} material={materials.initialShadingGroup} />
      </group>
    </group>
  )
}

useGLTF.preload('/Desk-EtJlOllzbf.glb')
