/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Dishwasher.glb -o /workspaces/windgapacademy/components/CityPackModels/Dishwasher.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Dishwasher.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Door.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishwasher1.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Pallet.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishes.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishes4.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishes5.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishes6.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishes7.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishes8.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishes9.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishes10.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Pallet1.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishes11.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishes1.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishes2.geometry} material={materials.lambert5SG} />
      <mesh geometry={nodes.Dishes3.geometry} material={materials.lambert5SG} />
    </group>
  );
}

useGLTF.preload("/Dishwasher.glb");
