/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Dish Washer.glb -o /workspaces/windgapacademy/components/CityPackModels/Dish Washer.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Dish Washer.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.DishWasher1.geometry}
        material={materials.MetalDishWasher1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.UpperBasker1DishWasher1.geometry}
        material={materials.SteelUpperBasker1DishWasher1}
        position={[0, 0.036, -0.015]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.LowerBasker1DishWasher1.geometry}
        material={materials.SteelUpperBasker2DishWasher1}
        position={[0, -0.358, -0.015]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[0, -0.449, 0.284]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Door1DishWasher1_1.geometry}
          material={materials.SteelDoor1DishWasher1}
        />
        <mesh
          geometry={nodes.Door1DishWasher1_2.geometry}
          material={materials.MetalDoor1DishWasher1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Dish Washer.glb");
