/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Donut.glb -o /workspaces/windgapacademy/components/CityPackModels/Donut.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Donut.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Donut1_1.geometry} material={materials.LightYellow} />
        <mesh geometry={nodes.Donut1_2.geometry} material={materials.PalePink} />
        <mesh geometry={nodes.Donut1_3.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Donut1_4.geometry} material={materials.Green} />
        <mesh geometry={nodes.Donut1_5.geometry} material={materials.Red} />
      </group>
    </group>
  );
}

useGLTF.preload("/Donut.glb");
