/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Donut Sprinkles.glb -o /workspaces/windgapacademy/components/CityPackModels/Donut Sprinkles.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Donut Sprinkles.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.donutSprinkles_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.donutSprinkles_1_1.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.donutSprinkles_1_2.geometry} material={materials.orange} />
      <mesh geometry={nodes.donutSprinkles_1_3.geometry} material={materials.yellow} />
      <mesh geometry={nodes.donutSprinkles_1_4.geometry} material={materials.green} />
    </group>
  );
}

useGLTF.preload("/Donut Sprinkles.glb");
