/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Doorway.glb -o /workspaces/windgapacademy/components/CityPackModels/Doorway.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Doorway.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.doorway.geometry} material={materials.wood} />
      <mesh geometry={nodes.doorway_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.door_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.door_1_1.geometry} material={materials.metal} />
    </group>
  );
}

useGLTF.preload("/Doorway.glb");
