/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Doorway Front.glb -o /workspaces/windgapacademy/components/CityPackModels/Doorway Front.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Doorway Front.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.doorwayFront.geometry} material={materials.carpetWhite} />
      <mesh geometry={nodes.doorwayFront_1.geometry} material={materials.carpetWhite} />
      <mesh geometry={nodes.door_1.geometry} material={materials.metal} />
      <mesh geometry={nodes.door_1_1.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.door_1_2.geometry} material={materials.glass} />
    </group>
  );
}

useGLTF.preload("/Doorway Front.glb");
