/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/door.glb -o /workspaces/windgapacademy/components/CityPackModels/door.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/door.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group507937764.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group1170317054.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group652015225.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group1139619275.geometry} material={materials.mat20} />
    </group>
  );
}

useGLTF.preload("/door.glb");
