/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Double Door Base Cabinet.glb -o /workspaces/windgapacademy/components/CityPackModels/Double Door Base Cabinet.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Double Door Base Cabinet.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.DoubleDoorbaseCabinet1_1.geometry}
          material={materials.WoodDoubleDoorbaseCabinet1}
        />
        <mesh
          geometry={nodes.DoubleDoorbaseCabinet1_2.geometry}
          material={materials.MarbleDoubleDoorbaseCabinet1}
        />
      </group>
      <group position={[-0.449, -0.067, 0.265]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.DoorR1SingleDoorbaseCabinet1_1.geometry}
          material={materials.WoodDoorR1SingleDoorbaseCabinet1}
        />
        <mesh
          geometry={nodes.DoorR1SingleDoorbaseCabinet1_2.geometry}
          material={materials.MetalDoorR1SingleDoorbaseCabinet1}
        />
      </group>
      <group position={[0.449, -0.067, 0.265]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.DoorL1SingleDoorbaseCabinet1_1.geometry}
          material={materials.WoodDoorL1SingleDoorbaseCabinet1}
        />
        <mesh
          geometry={nodes.DoorL1SingleDoorbaseCabinet1_2.geometry}
          material={materials.MetalDoorL1SingleDoorbaseCabinet1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Double Door Base Cabinet.glb");
