/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Double Bed.glb -o /workspaces/windgapacademy/components/CityPackModels/Double Bed.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Double Bed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Pillow1_DoubleBed1.geometry}
        material={materials.Pillow1_DoubleBed1}
        position={[-0.445, 0.095, -1.014]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Pillow2_DoubleBed1.geometry}
        material={materials.Pillow2_DoubleBed1}
        position={[0.416, 0.095, -1.031]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Blanked_DoubleBed1.geometry}
        material={materials.Blanked1_DoubleBed1}
        position={[0, -0.211, 0.058]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[0, 0.018, -0.22]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.DoubleBed1_1.geometry} material={materials.Mattress1DoubleBed1} />
        <mesh geometry={nodes.DoubleBed1_2.geometry} material={materials.Wood1DoubleBed1} />
      </group>
    </group>
  );
}

useGLTF.preload("/Double Bed.glb");
