/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Double Door Tall Cabinet.glb -o /workspaces/windgapacademy/components/CityPackModels/Double Door Tall Cabinet.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Double Door Tall Cabinet.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.DoubleDoorTallCabinet1.geometry}
        material={materials.WoodDoubleDoorTallCabinet1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[0.454, -0.09, 0.312]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.DoorL1DoubleDoorTallCabinet1_1.geometry}
          material={materials.WoodDoorL1DoubleDoorTallCabinet1}
        />
        <mesh
          geometry={nodes.DoorL1DoubleDoorTallCabinet1_2.geometry}
          material={materials.MetalDoorL1DoubleDoorTallCabinet1}
        />
      </group>
      <group position={[-0.454, -0.09, 0.312]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.DoorR1DoubleDoorTallCabinet1_1.geometry}
          material={materials.WoodDoorR1DoubleDoorTallCabinet1}
        />
        <mesh
          geometry={nodes.DoorR1DoubleDoorTallCabinet1_2.geometry}
          material={materials.MetalDoorR1DoubleDoorTallCabinet1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Double Door Tall Cabinet.glb");
