/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Drawers Base Cabinet.glb -o /workspaces/windgapacademy/components/CityPackModels/Drawers Base Cabinet.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Drawers Base Cabinet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DrawersBaseCabinet.geometry} material={materials.Wood1DrawersBaseCabinet} position={[0, 0.098, 0.021]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <group position={[0, 0.332, 0.222]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer1DrawersBaseCabinet_1.geometry} material={materials.Wood1Drawer1DrawersBaseCabinet} />
        <mesh geometry={nodes.Drawer1DrawersBaseCabinet_2.geometry} material={materials.Metal1Drawer1DrawersBaseCabinet} />
      </group>
      <group position={[0, 0.139, 0.222]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer2DrawersBaseCabinet_1.geometry} material={materials.Wood1Drawer2DrawersBaseCabinet} />
        <mesh geometry={nodes.Drawer2DrawersBaseCabinet_2.geometry} material={materials.Metal1Drawer2DrawersBaseCabinet} />
      </group>
      <group position={[0, -0.051, 0.001]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer3DrawersBaseCabinet_1.geometry} material={materials.Wood1Drawer3DrawersBaseCabinet} />
        <mesh geometry={nodes.Drawer3DrawersBaseCabinet_2.geometry} material={materials.Metal1Drawer3DrawersBaseCabinet} />
      </group>
      <group position={[0, -0.243, 0.001]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer4DrawersBaseCabinet_1.geometry} material={materials.Wood1Drawer4DrawersBaseCabinet} />
        <mesh geometry={nodes.Drawer4DrawersBaseCabinet_2.geometry} material={materials.Metal1Drawer4DrawersBaseCabinet} />
      </group>
    </group>
  )
}

useGLTF.preload('/Drawers Base Cabinet.glb')
