/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Drawers Double Door Bas.glb -o /workspaces/windgapacademy/components/CityPackModels/Drawers Double Door Bas.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Drawers Double Door Bas.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DrawersDoubleDoorbaseCabinet1.geometry} material={materials.Wood1DrawersDoubleDoorbaseCabinet1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <group position={[-0.449, -0.067, 0.265]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.DoorR1SingleDoorbaseCabinet1_1.geometry} material={materials.Wood1DoorR1SingleDoorbaseCabinet1} />
        <mesh geometry={nodes.DoorR1SingleDoorbaseCabinet1_2.geometry} material={materials.Metal1DoorR1SingleDoorbaseCabinet1} />
      </group>
      <group position={[0.449, -0.067, 0.265]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.DoorL1SingleDoorbaseCabinet1_1.geometry} material={materials.Wood1DoorL1SingleDoorbaseCabinet1} />
        <mesh geometry={nodes.DoorL1SingleDoorbaseCabinet1_2.geometry} material={materials.Metal1DoorL1SingleDoorbaseCabinet1} />
      </group>
      <group position={[0.237, 0.222, 0.203]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer2DrawersDoubleDoorbaseCabinet1_1.geometry} material={materials.Wood1Drawer2DrawersDoubleDoorbaseCabinet1} />
        <mesh geometry={nodes.Drawer2DrawersDoubleDoorbaseCabinet1_2.geometry} material={materials.Metal1Drawer2DrawersDoubleDoorbaseCabinet1} />
      </group>
      <group position={[-0.237, 0.221, 0.236]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer1DrawersDoubleDoorbaseCabinet1_1.geometry} material={materials.Metal1Drawer1DrawersDoubleDoorbaseCabinet1} />
        <mesh geometry={nodes.Drawer1DrawersDoubleDoorbaseCabinet1_2.geometry} material={materials.Wood1Drawer1DrawersDoubleDoorbaseCabinet1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Drawers Double Door Bas.glb')
