/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Drum stick.glb -o /workspaces/windgapacademy/components/CityPackModels/Drum stick.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Drum stick.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Drumstick_Circle007.geometry} material={materials.DD9944} />
    </group>
  )
}

useGLTF.preload('/Drum stick.glb')
