/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Drum Set.glb -o /workspaces/windgapacademy/components/CityPackModels/Drum Set.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Drum Set.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.DrumSet1_1.geometry} material={materials.Metal1DrumSet1} />
        <mesh geometry={nodes.DrumSet1_2.geometry} material={materials.Wood1DrumSet1} />
        <mesh geometry={nodes.DrumSet1_3.geometry} material={materials.Wood3DrumSet1} />
        <mesh geometry={nodes.DrumSet1_4.geometry} material={materials.Steel1DrumSet1} />
        <mesh geometry={nodes.DrumSet1_5.geometry} material={materials.Leather1DrumSet1} />
        <mesh geometry={nodes.DrumSet1_6.geometry} material={materials.Wood2DrumSet1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Drum Set.glb')
