/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Dual Monitors on sit-stand arm.glb -o /workspaces/windgapacademy/components/CityPackModels/Dual Monitors on sit-stand arm.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Dual Monitors on sit-stand arm.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1219313228.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1783798096.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group625259463.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group112678593.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group575146565.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1462626064.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1746518091.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group2060347243.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group929043094.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group2063576334.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1698824667.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group2070617275.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group710626981.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group2128326706.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group974294459.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1658787459.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group1896072715.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group451364077.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group786212531.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh329542522.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh329542522_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh576947092.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh576947092_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh150401702.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh150401702_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh860618825.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh860618825_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh860618825_2.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1691283673.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1691283673_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1691283673_2.geometry} material={materials.mat23} />
    </group>
  );
}

useGLTF.preload("/Dual Monitors on sit-stand arm.glb");
