/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Dumbell.glb -o /workspaces/windgapacademy/components/CityPackModels/Dumbell.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Dumbell.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Dumbell1_1.geometry} material={materials.IronDumbell1} />
        <mesh geometry={nodes.Dumbell1_2.geometry} material={materials.SteelDumbell1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Dumbell.glb')
