/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Dumpster.glb -o /workspaces/windgapacademy/components/CityPackModels/Dumpster.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Dumpster.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={58.6}>
        <mesh geometry={nodes.TrashContainer_1.geometry} material={materials.DarkGrey} />
        <mesh geometry={nodes.TrashContainer_2.geometry} material={materials.Green} />
        <mesh geometry={nodes.TrashContainer_3.geometry} material={materials.Grey} />
      </group>
    </group>
  );
}

useGLTF.preload("/Dumpster.glb");
