/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Dunnart.glb -o /workspaces/windgapacademy/components/CityPackModels/Dunnart.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Dunnart.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.M_eyes.geometry} material={materials.eyes} />
      <mesh geometry={nodes["M_body_-Mesh"].geometry} material={materials.Dunnart} />
      <mesh geometry={nodes["M_body_-Mesh_1"].geometry} material={materials.Tail} />
    </group>
  );
}

useGLTF.preload("/Dunnart.glb");
