/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Egg Cup.glb -o /workspaces/windgapacademy/components/CityPackModels/Egg Cup.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Egg Cup.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.eggCup_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.eggCup_1_1.geometry} material={materials.greyLight} />
    </group>
  );
}

useGLTF.preload("/Egg Cup.glb");
