/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Egg Cooked.glb -o /workspaces/windgapacademy/components/CityPackModels/Egg Cooked.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Egg Cooked.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.eggCooked_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.eggCooked_1_1.geometry} material={materials.yellow} />
    </group>
  );
}

useGLTF.preload("/Egg Cooked.glb");
