/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Electric guitar.glb -o /workspaces/windgapacademy/components/CityPackModels/Electric guitar.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Electric guitar.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ElectricGuitar_mesh.geometry} material={materials.lambert2SG} />
    </group>
  );
}

useGLTF.preload("/Electric guitar.glb");
