/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Electric Guitar Effects Pedal.glb -o /workspaces/windgapacademy/components/CityPackModels/Electric Guitar Effects Pedal.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Electric Guitar Effects Pedal.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group392190358.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1655281629.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group718641998.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1667536579.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group81912816.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1411390515.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group2103703536.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1543772656.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group32996253.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1587522966.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1587522966_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1118640416.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1118640416_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh332766569.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh332766569_1.geometry} material={materials.mat23} />
    </group>
  )
}

useGLTF.preload('/Electric Guitar Effects Pedal.glb')
