/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Electric Oven.glb -o /workspaces/windgapacademy/components/CityPackModels/Electric Oven.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Electric Oven.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.appliance_electric_oven_knob_Cube260.geometry}
        material={materials["Solid.080"]}
      />
      <mesh
        geometry={nodes.appliance_electric_oven_knob001_Cube262.geometry}
        material={materials["Solid.080"]}
      />
      <mesh
        geometry={nodes.appliance_electric_oven_knob002_Cube270.geometry}
        material={materials["Solid.080"]}
      />
      <mesh
        geometry={nodes.appliance_electric_oven_rack_Cube291.geometry}
        material={materials["Solid.080"]}
      />
      <mesh
        geometry={nodes.appliance_electric_oven_tray_Cube292.geometry}
        material={materials["Solid.080"]}
      />
      <mesh
        geometry={nodes["appliance_electric_oven_door_Cube254-Mesh"].geometry}
        material={materials["Solid.080"]}
      />
      <mesh
        geometry={nodes["appliance_electric_oven_door_Cube254-Mesh_1"].geometry}
        material={materials["Solid_-_75%.001"]}
      />
      <mesh
        geometry={nodes["appliance_electric_oven_Cube253-Mesh"].geometry}
        material={materials["Solid.080"]}
      />
      <mesh
        geometry={nodes["appliance_electric_oven_Cube253-Mesh_1"].geometry}
        material={materials.Emissive}
      />
    </group>
  );
}

useGLTF.preload("/Electric Oven.glb");
