/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Espresso Pot.glb -o /workspaces/windgapacademy/components/CityPackModels/Espresso Pot.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Espresso Pot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Espresso_Pot.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/Espresso Pot.glb')
