/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Executive Desk.glb -o /workspaces/windgapacademy/components/CityPackModels/Executive Desk.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Executive Desk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ExecutiveDesk1.geometry} material={materials.WoodExecutiveDesk1} position={[0, 0.431, -0.083]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <group position={[0.742, 0.53, 0.255]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer6_ExecutiveDesk1_1.geometry} material={materials.Wood1Drawer6_ExecutiveDesk1} />
        <mesh geometry={nodes.Drawer6_ExecutiveDesk1_2.geometry} material={materials.Metal1Drawer6_ExecutiveDesk1} />
      </group>
      <group position={[-0.742, 0.741, 0.255]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer1_ExecutiveDesk1_1.geometry} material={materials.Wood1Drawer1_ExecutiveDesk1} />
        <mesh geometry={nodes.Drawer1_ExecutiveDesk1_2.geometry} material={materials.Metal1Drawer1_ExecutiveDesk1} />
      </group>
      <group position={[-0.742, 0.53, 0.255]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer2_ExecutiveDesk1_1.geometry} material={materials.Wood1Drawer2_ExecutiveDesk1} />
        <mesh geometry={nodes.Drawer2_ExecutiveDesk1_2.geometry} material={materials.Metal1Drawer2_ExecutiveDesk1} />
      </group>
      <group position={[-0.742, 0.248, 0.255]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer3_ExecutiveDesk1_1.geometry} material={materials.Wood1Drawer3_ExecutiveDesk1} />
        <mesh geometry={nodes.Drawer3_ExecutiveDesk1_2.geometry} material={materials.Metal1Drawer3_ExecutiveDesk1} />
      </group>
      <group position={[0.742, 0.741, 0.255]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer5_ExecutiveDesk1_1.geometry} material={materials.Wood1Drawer5_ExecutiveDesk1} />
        <mesh geometry={nodes.Drawer5_ExecutiveDesk1_2.geometry} material={materials.Metal1Drawer5_ExecutiveDesk1} />
      </group>
      <group position={[0.742, 0.248, 0.255]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer7_ExecutiveDesk1_1.geometry} material={materials.Wood1Drawer7_ExecutiveDesk1} />
        <mesh geometry={nodes.Drawer7_ExecutiveDesk1_2.geometry} material={materials.Metal1Drawer7_ExecutiveDesk1} />
      </group>
      <group position={[0, 0.744, 0.319]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer4_ExecutiveDesk1_1.geometry} material={materials.Wood1Drawer4_ExecutiveDesk1} />
        <mesh geometry={nodes.Drawer4_ExecutiveDesk1_2.geometry} material={materials.Metal1Drawer4_ExecutiveDesk1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Executive Desk.glb')
