/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fan.glb -o /workspaces/windgapacademy/components/CityPackModels/Fan.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Fan.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Fan1_1.geometry} material={materials.MetalFan1} />
      <mesh geometry={nodes.Fan1_2.geometry} material={materials.LightFan1} />
    </group>
  )
}

useGLTF.preload('/Fan.glb')
