/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fancy Donuts.glb -o /workspaces/windgapacademy/components/CityPackModels/Fancy Donuts.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Fancy Donuts.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group419909856.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1895318755.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1895318755_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh425272709.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh425272709_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh377362996.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh377362996_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1307717322.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1307717322_1.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1307717322_2.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1307717322_3.geometry} material={materials.mat24} />
      <mesh geometry={nodes.mesh1307717322_4.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1307717322_5.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1307717322_6.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh1307717322_7.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1307717322_8.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1307717322_9.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1307717322_10.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1307717322_11.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh946731157.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh946731157_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1418326412.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1418326412_1.geometry} material={materials.mat15} />
    </group>
  );
}

useGLTF.preload("/Fancy Donuts.glb");
