/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fence Piece.glb -o /workspaces/windgapacademy/components/CityPackModels/Fence Piece.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Fence Piece.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.272, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={56}>
        <mesh geometry={nodes.FencePiece_1.geometry} material={materials.brick_shade1} />
        <mesh geometry={nodes.FencePiece_2.geometry} material={materials.brick_shade2} />
        <mesh geometry={nodes.FencePiece_3.geometry} material={materials.sandstone_light} />
        <mesh geometry={nodes.FencePiece_4.geometry} material={materials.metal_fence} />
      </group>
    </group>
  );
}

useGLTF.preload("/Fence Piece.glb");
