/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fire Exit Sign-0ywPpb36cyK.glb -o /workspaces/windgapacademy/components/CityPackModels/Fire Exit Sign-0ywPpb36cyK.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Fire Exit Sign-0ywPpb36cyK.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Fire_exit.geometry} material={materials['01___Default']} />
    </group>
  )
}

useGLTF.preload('/Fire Exit Sign-0ywPpb36cyK.glb')
