/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fire Exit Sign.glb -o /workspaces/windgapacademy/components/CityPackModels/Fire Exit Sign.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Fire Exit Sign.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.161, 0.354, 0]} rotation={[0, Math.PI / 2, 0]} scale={[21.75, 27.937, 27.937]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials.Logo} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.White} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials.Green} />
      </group>
    </group>
  )
}

useGLTF.preload('/Fire Exit Sign.glb')
