/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fire Exit.glb -o /workspaces/windgapacademy/components/CityPackModels/Fire Exit.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Fire Exit.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.FireExit.geometry}
        material={materials.metal_shade1}
        position={[-0.112, 0.665, -0.246]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={60}
      />
    </group>
  );
}

useGLTF.preload("/Fire Exit.glb");
