/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fireplace.glb -o /workspaces/windgapacademy/components/CityPackModels/Fireplace.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Fireplace.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Fireplace1_1.geometry} material={materials.WoodFireplace1} />
        <mesh geometry={nodes.Fireplace1_2.geometry} material={materials.Fireplace1} />
        <mesh geometry={nodes.Fireplace1_3.geometry} material={materials.MetalFireplace1} />
        <mesh geometry={nodes.Fireplace1_4.geometry} material={materials.Brick3Fireplace1} />
        <mesh geometry={nodes.Fireplace1_5.geometry} material={materials.Brick2Fireplace1} />
        <mesh geometry={nodes.Fireplace1_6.geometry} material={materials.Brick1Fireplace1} />
      </group>
    </group>
  );
}

useGLTF.preload("/Fireplace.glb");
