/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fire Place.glb -o /workspaces/windgapacademy/components/CityPackModels/Fire Place.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Fire Place.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FirePlace_1.geometry} material={materials.BricksFIrePlace} />
      <mesh geometry={nodes.FirePlace_2.geometry} material={materials.WoodFirePlace} />
      <mesh geometry={nodes.FirePlace_3.geometry} material={materials.ShieldFirePlace} />
    </group>
  );
}

useGLTF.preload("/Fire Place.glb");
