/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fire Extinguisher.glb -o /workspaces/windgapacademy/components/CityPackModels/Fire Extinguisher.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Fire Extinguisher.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Top_Bolt_Mesh001.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.Bottom_bolt_Mesh002.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.Extinguisher_Mesh003.geometry} material={materials.lambert2} />
    </group>
  )
}

useGLTF.preload('/Fire Extinguisher.glb')
