/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fish Bones.glb -o /workspaces/windgapacademy/components/CityPackModels/Fish Bones.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Fish Bones.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fishBones.geometry} material={materials.greyLight} />
    </group>
  );
}

useGLTF.preload("/Fish Bones.glb");
