/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fish.glb -o /workspaces/windgapacademy/components/CityPackModels/Fish.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Fish.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fish_1.geometry} material={materials.pink} />
      <mesh geometry={nodes.fish_1_1.geometry} material={materials.greyLight} />
      <mesh geometry={nodes.fish_1_2.geometry} material={materials._defaultMat} />
    </group>
  );
}

useGLTF.preload("/Fish.glb");
