/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Floor Hole.glb -o /workspaces/windgapacademy/components/CityPackModels/Floor Hole.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Floor Hole.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.003, 0, -0.011]} rotation={[-Math.PI / 2, 0, 0]} scale={60}>
        <mesh geometry={nodes.FloorHole_1.geometry} material={materials.pavement} />
        <mesh geometry={nodes.FloorHole_2.geometry} material={materials.dirt} />
      </group>
    </group>
  );
}

useGLTF.preload("/Floor Hole.glb");
