/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Floor Lamp.glb -o /workspaces/windgapacademy/components/CityPackModels/Floor Lamp.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Floor Lamp.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.FloorLamp1_1.geometry} material={materials.MetalFloorLamp1} />
        <mesh geometry={nodes.FloorLamp1_2.geometry} material={materials.ShadeFloorLamp1} />
        <mesh geometry={nodes.FloorLamp1_3.geometry} material={materials.LampFloorLamp1} />
      </group>
    </group>
  );
}

useGLTF.preload("/Floor Lamp.glb");
