/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Floor Monitor.glb -o /workspaces/windgapacademy/components/CityPackModels/Floor Monitor.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Floor Monitor.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1711254561.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1156748319.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1406311733.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group972682665.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group719040422.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1473385859.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group109501637.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1699706484.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1231104907.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1990572017.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1990572017_1.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh355800739.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh355800739_1.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh355800739_2.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1484190439.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1484190439_1.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1682937251.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1682937251_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh268863367.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh268863367_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1699352642.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1699352642_1.geometry} material={materials.mat14} />
    </group>
  );
}

useGLTF.preload("/Floor Monitor.glb");
