/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Petal-niuBUEJdvM.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Petal-niuBUEJdvM.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Flower Petal-niuBUEJdvM.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Petal_4.geometry} material={materials.Flowers} />
    </group>
  );
}

useGLTF.preload("/Flower Petal-niuBUEJdvM.glb");
