/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Pot.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Pot.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Flower Pot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FlowerPot7_1.geometry} material={materials.VaseFlowerPot7} />
      <mesh geometry={nodes.FlowerPot7_2.geometry} material={materials.GroundFlowerPot7} />
      <mesh geometry={nodes.FlowerPot7_3.geometry} material={materials.TrunkFlowerPot7} />
      <mesh geometry={nodes.FlowerPot7_4.geometry} material={materials.LeafFlowerPot7} />
      <mesh geometry={nodes.FlowerPot7_5.geometry} material={materials.FruitFlowerPot7} />
    </group>
  )
}

useGLTF.preload('/Flower Pot.glb')
