/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Pot-F8zLx6wGG8.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Pot-F8zLx6wGG8.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Flower Pot-F8zLx6wGG8.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FlowerPot5_1.geometry} material={materials["VaseFlowerPot5.001"]} />
      <mesh geometry={nodes.FlowerPot5_2.geometry} material={materials["GroundFlowerPot5.001"]} />
      <mesh geometry={nodes.FlowerPot5_3.geometry} material={materials["CactusFlowerPot5.001"]} />
      <mesh geometry={nodes.FlowerPot5_4.geometry} material={materials["GoldFlowerPot5.001"]} />
      <mesh geometry={nodes.FlowerPot5_5.geometry} material={materials["FlowerFlowerPot5.001"]} />
    </group>
  );
}

useGLTF.preload("/Flower Pot-F8zLx6wGG8.glb");
