/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Bed.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Bed.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Flower Bed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FlowerBed2_1.geometry} material={materials.ConcreteFlowerBed2} />
      <mesh geometry={nodes.FlowerBed2_2.geometry} material={materials.GroundFlowerBed5} />
    </group>
  )
}

useGLTF.preload('/Flower Bed.glb')
