/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Bed-dM9hXXth1I.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Bed-dM9hXXth1I.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Flower Bed-dM9hXXth1I.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FlowerBed4_1.geometry} material={materials.ConcreteFlowerBed4} />
      <mesh geometry={nodes.FlowerBed4_2.geometry} material={materials.GroundFlowerBed4} />
    </group>
  );
}

useGLTF.preload("/Flower Bed-dM9hXXth1I.glb");
