/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Single-GvfHo0roi3.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Single-GvfHo0roi3.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Flower Single-GvfHo0roi3.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Flower_4_Single_1.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.Flower_4_Single_2.geometry} material={materials.Flowers} />
    </group>
  );
}

useGLTF.preload("/Flower Single-GvfHo0roi3.glb");
