/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Pot-k1FsCQTgWu.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Pot-k1FsCQTgWu.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Flower Pot-k1FsCQTgWu.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FlowerPot1_1.geometry} material={materials.VaseFlowerPot1} />
      <mesh geometry={nodes.FlowerPot1_2.geometry} material={materials.GroundPot1} />
      <mesh geometry={nodes.FlowerPot1_3.geometry} material={materials.FlowerPot} />
    </group>
  );
}

useGLTF.preload("/Flower Pot-k1FsCQTgWu.glb");
