/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Pot-u0CrZnpykb.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Pot-u0CrZnpykb.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Flower Pot-u0CrZnpykb.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FlowerPot6_1.geometry} material={materials.VaseFlowerPot6} />
      <mesh geometry={nodes.FlowerPot6_2.geometry} material={materials.GroundFlowerPot6} />
      <mesh geometry={nodes.FlowerPot6_3.geometry} material={materials.LeafsFlowerPot6} />
      <mesh geometry={nodes.FlowerPot6_4.geometry} material={materials.FlowersFlowerPot6} />
    </group>
  );
}

useGLTF.preload("/Flower Pot-u0CrZnpykb.glb");
