/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Single.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Single.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Flower Single.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Flower_3_Single_1.geometry} material={materials.Flowers} />
      <mesh geometry={nodes.Flower_3_Single_2.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/Flower Single.glb')
