/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Pot-Kgt363WkKd.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Pot-Kgt363WkKd.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Flower Pot-Kgt363WkKd.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FlowerPot4_1.geometry} material={materials.VaseFlowerPot4} />
      <mesh geometry={nodes.FlowerPot4_2.geometry} material={materials.GroundFlowerPot4} />
      <mesh geometry={nodes.FlowerPot4_3.geometry} material={materials.PlantFlowerPot4} />
    </group>
  );
}

useGLTF.preload("/Flower Pot-Kgt363WkKd.glb");
