/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flowers.glb -o /workspaces/windgapacademy/components/CityPackModels/Flowers.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Flowers.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Flowers1_1.geometry} material={materials.Leaf2Impatiens} />
      <mesh geometry={nodes.Flowers1_2.geometry} material={materials.LeafImpatiens} />
      <mesh geometry={nodes.Flowers1_3.geometry} material={materials.Flower1Impatiens} />
      <mesh geometry={nodes.Flowers1_4.geometry} material={materials.Flower2Impatiens} />
    </group>
  )
}

useGLTF.preload('/Flowers.glb')
