/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Bed-eUCvK3Oq9z.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Bed-eUCvK3Oq9z.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Flower Bed-eUCvK3Oq9z.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FlowerBed3_1.geometry} material={materials.ConcreteFlowerBed3} />
      <mesh geometry={nodes.FlowerBed3_2.geometry} material={materials.GroundFlowerBed3} />
    </group>
  );
}

useGLTF.preload("/Flower Bed-eUCvK3Oq9z.glb");
