/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Pot-FNqGPLKY0V.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Pot-FNqGPLKY0V.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Flower Pot-FNqGPLKY0V.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FlowerPot8_1.geometry} material={materials.LeafFlowerPot8} />
      <mesh geometry={nodes.FlowerPot8_2.geometry} material={materials.VaseFlowerPot8} />
      <mesh geometry={nodes.FlowerPot8_3.geometry} material={materials.GroundFlowerPot8} />
    </group>
  );
}

useGLTF.preload("/Flower Pot-FNqGPLKY0V.glb");
