/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Bed-wibWtE6p8L.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Bed-wibWtE6p8L.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Flower Bed-wibWtE6p8L.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FlowerBed6_1.geometry} material={materials.ConcreteFlowerBed6} />
      <mesh geometry={nodes.FlowerBed6_2.geometry} material={materials.GroundFlowerBed6} />
    </group>
  );
}

useGLTF.preload("/Flower Bed-wibWtE6p8L.glb");
