/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flower Group.glb -o /workspaces/windgapacademy/components/CityPackModels/Flower Group.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Flower Group.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Flower_3_Group_1.geometry} material={materials.Flowers} />
      <mesh geometry={nodes.Flower_3_Group_2.geometry} material={materials.Leaves} />
    </group>
  );
}

useGLTF.preload("/Flower Group.glb");
