/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Flute.glb -o /workspaces/windgapacademy/components/CityPackModels/Flute.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Flute.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Flute1_1.geometry} material={materials.Wood1Flute1} />
        <mesh geometry={nodes.Flute1_2.geometry} material={materials.Wood2Flute1} />
      </group>
    </group>
  );
}

useGLTF.preload("/Flute.glb");
