/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Football.glb -o /workspaces/windgapacademy/components/CityPackModels/Football.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Football.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.FootballBall1_1.geometry} material={materials.White1FootballBall1} />
        <mesh geometry={nodes.FootballBall1_2.geometry} material={materials.Black1FootballBall1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Football.glb')
