/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fortress.glb -o /workspaces/windgapacademy/components/CityPackModels/Fortress.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Fortress.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Fortress.geometry} material={materials.Diffuse_color} scale={100} />
    </group>
  )
}

useGLTF.preload('/Fortress.glb')
