/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fox.glb -o /workspaces/windgapacademy/components/CityPackModels/Fox.jsx 
*/

import { useGLTF, useAnimations, useGraph } from "@react-three/drei";

import React, { useEffect } from "react";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/Fox.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions, names } = useAnimations(animations, group);
  
  // Play first animation if available
  useEffect(() => {
    if (names.length > 0 && actions[names[0]]) {
      actions[names[0]].reset().fadeIn(0.5).play();
    }
    return () => names.forEach(name => actions[name]?.fadeOut(0.5));
  }, [actions, names]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="AnimalArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group name="Fox" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Fox_1"
              geometry={nodes.Fox_1.geometry}
              material={materials.Main}
              skeleton={nodes.Fox_1.skeleton}
            />
            <skinnedMesh
              name="Fox_2"
              geometry={nodes.Fox_2.geometry}
              material={materials.Main_Light}
              skeleton={nodes.Fox_2.skeleton}
            />
            <skinnedMesh
              name="Fox_3"
              geometry={nodes.Fox_3.geometry}
              material={materials.Grey}
              skeleton={nodes.Fox_3.skeleton}
            />
            <skinnedMesh
              name="Fox_4"
              geometry={nodes.Fox_4.geometry}
              material={materials.Black}
              skeleton={nodes.Fox_4.skeleton}
            />
            <skinnedMesh
              name="Fox_5"
              geometry={nodes.Fox_5.geometry}
              material={materials.Eyes}
              skeleton={nodes.Fox_5.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Fox.glb");
