/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Frappe.glb -o /workspaces/windgapacademy/components/CityPackModels/Frappe.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Frappe.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.straw.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.frappe_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.frappe_1_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.frappe_1_2.geometry} material={materials.brownLight} />
    </group>
  );
}

useGLTF.preload("/Frappe.glb");
