/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fridge.glb -o /workspaces/windgapacademy/components/CityPackModels/Fridge.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Fridge.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.TopFridge1.geometry}
        material={materials.MetalTopFridge1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Drawer2_TopFridge1.geometry}
        material={materials.MetalDrawer2_TopFridge1}
        position={[0.22, -0.808, 0.073]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[0.522, -0.321, 0.316]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.DownDoor1_TopFridge1_1.geometry}
          material={materials.SteelUpperDoor2_TopFridge1}
        />
        <mesh
          geometry={nodes.DownDoor1_TopFridge1_2.geometry}
          material={materials.MetalDownDoor2_TopFridge1}
        />
      </group>
      <mesh
        geometry={nodes.Drawer1_TopFridge1.geometry}
        material={materials.MetalDrawer1_TopFridge1}
        position={[-0.257, -0.808, 0.073]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[0.522, 0.747, 0.316]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.UpperDoor1_TopFridge1_1.geometry}
          material={materials.SteelUpperDoor1_TopFridge1}
        />
        <mesh
          geometry={nodes.UpperDoor1_TopFridge1_2.geometry}
          material={materials.MetalUpperDoor1_TopFridge1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Fridge.glb");
