/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fries.glb -o /workspaces/windgapacademy/components/CityPackModels/Fries.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Fries.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fries.geometry} material={materials.red} />
      <mesh geometry={nodes.fries_1.geometry} material={materials.yellow} />
    </group>
  )
}

useGLTF.preload('/Fries.glb')
