/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Fruit Bowl.glb -o /workspaces/windgapacademy/components/CityPackModels/Fruit Bowl.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Fruit Bowl.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FruitBowl.geometry} material={materials.Material} scale={100} />
    </group>
  );
}

useGLTF.preload("/Fruit Bowl.glb");
