/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Frying Pan.glb -o /workspaces/windgapacademy/components/CityPackModels/Frying Pan.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Frying Pan.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fryingPan_1.geometry} material={materials.greyDark} />
      <mesh geometry={nodes.fryingPan_1_1.geometry} material={materials.brown} />
    </group>
  );
}

useGLTF.preload("/Frying Pan.glb");
