/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Gas Stove.glb -o /workspaces/windgapacademy/components/CityPackModels/Gas Stove.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Gas Stove.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.GasStove1_1.geometry} material={materials.IronGasStove1} />
        <mesh geometry={nodes.GasStove1_2.geometry} material={materials.MetalGasStove1} />
      </group>
      <group position={[0, -0.678, 0.376]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Door1GasStove1_1.geometry} material={materials.SteelDoor1GasStove1} />
        <mesh geometry={nodes.Door1GasStove1_2.geometry} material={materials.MetalDoor1GasStove1} />
        <mesh geometry={nodes.Door1GasStove1_3.geometry} material={materials.GlassDoor1GasStove1} />
      </group>
      <mesh geometry={nodes.Button4GasStove1.geometry} material={materials.MetalButton4GasStove} position={[-0.006, -0.059, 0.383]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Button3GasStove1.geometry} material={materials.MetalButton3GasStove} position={[-0.098, -0.059, 0.383]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Button2GasStove1.geometry} material={materials.MetalButton2GasStove} position={[-0.19, -0.059, 0.383]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Button1GasStove1.geometry} material={materials.MetalButton1GasStove1} position={[-0.282, -0.059, 0.383]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Button5GasStove1.geometry} material={materials.MetalButton5GasStove} position={[0.186, -0.059, 0.389]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Button6GasStove1.geometry} material={materials.MetalButton6GasStove} position={[0.278, -0.059, 0.389]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Gas Stove.glb')
