/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Gazebo.glb -o /workspaces/windgapacademy/components/CityPackModels/Gazebo.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Gazebo.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Gazebo1_1.geometry} material={materials.Gazebo1} />
      <mesh geometry={nodes.Gazebo1_2.geometry} material={materials.RoofGazebo1} />
    </group>
  );
}

useGLTF.preload("/Gazebo.glb");
