/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Ginger Bread.glb -o /workspaces/windgapacademy/components/CityPackModels/Ginger Bread.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Ginger Bread.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.gingerBread_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.gingerBread_1_1.geometry} material={materials.brown} />
    </group>
  );
}

useGLTF.preload("/Ginger Bread.glb");
