/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Ginger Bread Cutter.glb -o /workspaces/windgapacademy/components/CityPackModels/Ginger Bread Cutter.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Ginger Bread Cutter.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.gingerBreadCutter.geometry} material={materials.white} />
    </group>
  );
}

useGLTF.preload("/Ginger Bread Cutter.glb");
