/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Glass Wine.glb -o /workspaces/windgapacademy/components/CityPackModels/Glass Wine.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Glass Wine.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.glassWine_1.geometry} material={materials._defaultMat} />
      <mesh
        geometry={nodes.glassWine_1_1.geometry}
        material={materials["[Translucent_Glass_Gray]"]}
      />
    </group>
  );
}

useGLTF.preload("/Glass Wine.glb");
