/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Grass.glb -o /workspaces/windgapacademy/components/CityPackModels/Grass.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Grass.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grass_Common_Short.geometry} material={materials.Grass} />
    </group>
  );
}

useGLTF.preload("/Grass.glb");
