/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Greenhouse.glb -o /workspaces/windgapacademy/components/CityPackModels/Greenhouse.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Greenhouse.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["greenhouse-Mesh"].geometry} material={materials.greenhouse_1} />
      <mesh geometry={nodes["greenhouse-Mesh_1"].geometry} material={materials.greenhouse_glass} />
    </group>
  );
}

useGLTF.preload("/Greenhouse.glb");
