/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Grill.glb -o /workspaces/windgapacademy/components/CityPackModels/Grill.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Grill.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grill1_1.geometry} material={materials.MetalGrill1} />
      <mesh geometry={nodes.Grill1_2.geometry} material={materials.Metal2Grill1} />
    </group>
  )
}

useGLTF.preload('/Grill.glb')
