/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Guitar.glb -o /workspaces/windgapacademy/components/CityPackModels/Guitar.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Guitar.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Guitar1_1.geometry} material={materials.Wood2Guitar1} />
        <mesh geometry={nodes.Guitar1_2.geometry} material={materials.Wood1Guitar1} />
        <mesh geometry={nodes.Guitar1_3.geometry} material={materials.Metal1Guitar1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Guitar.glb')
