/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Gymmat.glb -o /workspaces/windgapacademy/components/CityPackModels/Gymmat.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Gymmat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Gymmat1.geometry} material={materials.Mat1Gymmat1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Gymmat.glb')
