/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Headphones.glb -o /workspaces/windgapacademy/components/CityPackModels/Headphones.jsx
*/

import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Headphones.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={14370}
        near={10}
        fov={26.991}
        position={[-38.857, 56.816, 72.961]}
        rotation={[-0.463, -0.425, -0.203]}
        scale={100}
      />
      <group
        position={[0, 36.495, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1467.302, 66.51, 96.401]}
      >
        <mesh geometry={nodes.Cube_1.geometry} material={materials.headholder} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials["ear parts"]} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.muffs} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials.SHpeakers} />
      </group>
    </group>
  );
}

useGLTF.preload("/Headphones.glb");
