/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Honey.glb -o /workspaces/windgapacademy/components/CityPackModels/Honey.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Honey.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.honey_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.honey_1_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.honey_1_2.geometry} material={materials.yellow} />
    </group>
  );
}

useGLTF.preload("/Honey.glb");
