/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Hot Dog.glb -o /workspaces/windgapacademy/components/CityPackModels/Hot Dog.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Hot Dog.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.hotDog.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.sausage.geometry} material={materials.brown} />
      <mesh geometry={nodes.sauce_1.geometry} material={materials.yellow} />
      <mesh geometry={nodes.sauce_1_1.geometry} material={materials.red} />
    </group>
  );
}

useGLTF.preload("/Hot Dog.glb");
