/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Houseplant-bfLOqIV5uP.glb -o /workspaces/windgapacademy/components/CityPackModels/Houseplant-bfLOqIV5uP.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Houseplant-bfLOqIV5uP.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Houseplant_7_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.Houseplant_7_2.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Houseplant_7_3.geometry} material={materials.Plant_Green} />
      </group>
    </group>
  );
}

useGLTF.preload("/Houseplant-bfLOqIV5uP.glb");
