/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Houseplant-IBLX2Jz90O.glb -o /workspaces/windgapacademy/components/CityPackModels/Houseplant-IBLX2Jz90O.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Houseplant-IBLX2Jz90O.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Houseplant_5_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.Houseplant_5_2.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Houseplant_5_3.geometry} material={materials.Plant_Green} />
      </group>
    </group>
  );
}

useGLTF.preload("/Houseplant-IBLX2Jz90O.glb");
