/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Houseplant-e9oRt-Ct6js.glb -o /workspaces/windgapacademy/components/CityPackModels/Houseplant-e9oRt-Ct6js.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Houseplant-e9oRt-Ct6js.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["plant_01_Cube006-Mesh"].geometry} material={materials["795548"]} />
      <mesh geometry={nodes["plant_01_Cube006-Mesh_1"].geometry} material={materials["8BC34A"]} />
      <mesh geometry={nodes["plant_01_Cube006-Mesh_2"].geometry} material={materials.F8BBD0} />
      <mesh geometry={nodes["plant_01_Cube006-Mesh_3"].geometry} material={materials["455A64"]} />
    </group>
  );
}

useGLTF.preload("/Houseplant-e9oRt-Ct6js.glb");
