/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Ice Cream.glb -o /workspaces/windgapacademy/components/CityPackModels/Ice Cream.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Ice Cream.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.iceCream_1.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.iceCream_1_1.geometry} material={materials.brownLight} />
    </group>
  );
}

useGLTF.preload("/Ice Cream.glb");
