/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Japanese Sedge.glb -o /workspaces/windgapacademy/components/CityPackModels/Japanese Sedge.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Japanese Sedge.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.JapaneseSedge1.geometry} material={materials.JapaneseSedge1} />
    </group>
  )
}

useGLTF.preload('/Japanese Sedge.glb')
