/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Kitchen Sink Faucet.glb -o /workspaces/windgapacademy/components/CityPackModels/Kitchen Sink Faucet.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Kitchen Sink Faucet.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Node-Mesh"].geometry} material={materials.mat15} />
      <mesh geometry={nodes["Node-Mesh_1"].geometry} material={materials.mat22} />
    </group>
  );
}

useGLTF.preload("/Kitchen Sink Faucet.glb");
