/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Kitchen Stool.glb -o /workspaces/windgapacademy/components/CityPackModels/Kitchen Stool.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Kitchen Stool.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.ModernKitchenStool1_1.geometry} material={materials.MetalModernKitchenStool1} />
        <mesh geometry={nodes.ModernKitchenStool1_2.geometry} material={materials.LeatherModernKitchenStool1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Kitchen Stool.glb')
