/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Kitchen Cabinet Corner.glb -o /workspaces/windgapacademy/components/CityPackModels/Kitchen Cabinet Corner.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Kitchen Cabinet Corner.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.kitchenCabinetUpperCorner.geometry} material={materials.wood} />
      <mesh geometry={nodes.kitchenCabinetUpperCorner_1.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/Kitchen Cabinet Corner.glb')
