/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Kitchen Microwave.glb -o /workspaces/windgapacademy/components/CityPackModels/Kitchen Microwave.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Kitchen Microwave.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.kitchenMicrowave_2.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.kitchenMicrowave_2_1.geometry} material={materials.carpetWhite} />
      <mesh geometry={nodes.kitchenMicrowave_2_2.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.kitchenMicrowave_3.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.kitchenMicrowave_3_1.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.kitchenMicrowave_3_2.geometry} material={materials.carpetWhite} />
      <mesh geometry={nodes.Group_1.geometry} material={materials.carpetWhite} />
      <mesh geometry={nodes.Group_1_1.geometry} material={materials.glass} />
      <mesh geometry={nodes.Group_1_2.geometry} material={materials.metalMedium} />
    </group>
  );
}

useGLTF.preload("/Kitchen Microwave.glb");
