/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Kitchen Scale.glb -o /workspaces/windgapacademy/components/CityPackModels/Kitchen Scale.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Kitchen Scale.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Kitchen_Scale.geometry} material={materials.Mat} />
    </group>
  );
}

useGLTF.preload("/Kitchen Scale.glb");
