/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/L Shaped Desk.glb -o /workspaces/windgapacademy/components/CityPackModels/L Shaped Desk.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/L Shaped Desk.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.LShapedDesk1_1.geometry} material={materials.MetalLShapedDesk1} />
        <mesh geometry={nodes.LShapedDesk1_2.geometry} material={materials.PlasticLShapedDesk1} />
      </group>
    </group>
  );
}

useGLTF.preload("/L Shaped Desk.glb");
