/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Lamp.glb -o /workspaces/windgapacademy/components/CityPackModels/Lamp.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Lamp.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lamp1_1.geometry} material={materials.WoodLamp1} />
      <mesh geometry={nodes.Lamp1_2.geometry} material={materials.CandleLamp1} />
      <mesh geometry={nodes.Lamp1_3.geometry} material={materials["RopeCandle1.001"]} />
    </group>
  );
}

useGLTF.preload("/Lamp.glb");
