/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Laptop bag.glb -o /workspaces/windgapacademy/components/CityPackModels/Laptop bag.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Laptop bag.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box008.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box009.geometry} material={materials["03___Default"]} />
      <mesh geometry={nodes.Box011.geometry} material={materials["03___Default"]} />
      <mesh geometry={nodes.Box012.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Text002.geometry} material={materials["_crayfishdiffuse-2"]} />
      <mesh geometry={nodes.Box013.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box014.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box010_1.geometry} material={materials["03___Default"]} />
      <mesh geometry={nodes.Box010_1_1.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box010_1_2.geometry} material={materials["02___Default"]} />
    </group>
  );
}

useGLTF.preload("/Laptop bag.glb");
