/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Large Wardrobe.glb -o /workspaces/windgapacademy/components/CityPackModels/Large Wardrobe.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Large Wardrobe.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.LargeWardrobe1.geometry}
        material={materials.Wood1LargeWardrobe1}
        position={[0, -0.077, -0.113]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[-1.238, 0.282, 0.104]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.ClosetDoorRight1_LargeWardrobe1_1.geometry}
          material={materials.Wood1ClosetDoorRight1_LargeWardrobe1}
        />
        <mesh
          geometry={nodes.ClosetDoorRight1_LargeWardrobe1_2.geometry}
          material={materials.Metal1ClosetDoorRight1_LargeWardrobe1}
        />
      </group>
      <group position={[-0.634, 0.282, 0.104]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.ClosetDoorLeft1_LargeWardrobe1_1.geometry}
          material={materials.Wood1ClosetDoorLeft1_LargeWardrobe1}
        />
        <mesh
          geometry={nodes.ClosetDoorLeft1_LargeWardrobe1_2.geometry}
          material={materials.Metal1ClosetDoorLeft1_LargeWardrobe1}
        />
      </group>
      <group position={[-0.612, 0.546, 0.107]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.ClosetDoorRight2_LargeWardrobe1_1.geometry}
          material={materials.Wood1ClosetDoorRight2_LargeWardrobe1}
        />
        <mesh
          geometry={nodes.ClosetDoorRight2_LargeWardrobe1_2.geometry}
          material={materials.Metal1ClosetDoorRight2_LargeWardrobe1}
        />
      </group>
      <group position={[0.612, 0.546, 0.107]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.ClosetDoorLeft2_LargeWardrobe1_1.geometry}
          material={materials.Wood1ClosetDoorLeft2_LargeWardrobe1}
        />
        <mesh
          geometry={nodes.ClosetDoorLeft2_LargeWardrobe1_2.geometry}
          material={materials.Metal1ClosetDoorLeft2_LargeWardrobe1}
        />
      </group>
      <group position={[0.634, 0.282, 0.104]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.ClosetDoorRight3_LargeWardrobe1_1.geometry}
          material={materials.Wood1ClosetDoorRight3_LargeWardrobe1}
        />
        <mesh
          geometry={nodes.ClosetDoorRight3_LargeWardrobe1_2.geometry}
          material={materials.Metal1ClosetDoorRight3_LargeWardrobe1}
        />
      </group>
      <group position={[1.238, 0.282, 0.104]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.ClosetDoorLeft3_LargeWardrobe1_1.geometry}
          material={materials.Wood1ClosetDoorLeft3_LargeWardrobe1}
        />
        <mesh
          geometry={nodes.ClosetDoorLeft3_LargeWardrobe1_2.geometry}
          material={materials.Metal1ClosetDoorLeft3_LargeWardrobe1}
        />
      </group>
      <group position={[0, -0.009, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer3_LargeWardrobe1_1.geometry}
          material={materials.Wood1Drawer3_LargeWardrobe1}
        />
        <mesh
          geometry={nodes.Drawer3_LargeWardrobe1_2.geometry}
          material={materials.Metal1Drawer3_LargeWardrobe1}
        />
      </group>
      <group position={[0, -0.009, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer4_LargeWardrobe1_1.geometry}
          material={materials.Wood1Drawer4_LargeWardrobe1}
        />
        <mesh
          geometry={nodes.Drawer4_LargeWardrobe1_2.geometry}
          material={materials.Metal1Drawer4_LargeWardrobe1}
        />
      </group>
      <group position={[0, -0.009, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer1_LargeWardrobe1_1.geometry}
          material={materials.Wood1Drawer1_LargeWardrobe1}
        />
        <mesh
          geometry={nodes.Drawer1_LargeWardrobe1_2.geometry}
          material={materials.Metal1Drawer1_LargeWardrobe1}
        />
      </group>
      <group position={[0, -0.009, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer2_LargeWardrobe1_1.geometry}
          material={materials.Wood1Drawer2_LargeWardrobe1}
        />
        <mesh
          geometry={nodes.Drawer2_LargeWardrobe1_2.geometry}
          material={materials.Metal1Drawer2_LargeWardrobe1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Large Wardrobe.glb");
