/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Leek.glb -o /workspaces/windgapacademy/components/CityPackModels/Leek.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Leek.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.leek_1.geometry} material={materials.green} />
      <mesh geometry={nodes.leek_1_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.leek_1_2.geometry} material={materials.greenDark} />
    </group>
  );
}

useGLTF.preload("/Leek.glb");
