/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Lemon Half.glb -o /workspaces/windgapacademy/components/CityPackModels/Lemon Half.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Lemon Half.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lemonHalf_1.geometry} material={materials.yellow} />
      <mesh geometry={nodes.lemonHalf_1_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.lemonHalf_1_2.geometry} material={materials.brownDark} />
    </group>
  );
}

useGLTF.preload("/Lemon Half.glb");
