/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Lemon.glb -o /workspaces/windgapacademy/components/CityPackModels/Lemon.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Lemon.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lemon_1.geometry} material={materials.yellow} />
      <mesh geometry={nodes.lemon_1_1.geometry} material={materials.brownDark} />
    </group>
  );
}

useGLTF.preload("/Lemon.glb");
