/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Light Floor.glb -o /workspaces/windgapacademy/components/CityPackModels/Light Floor.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Light Floor.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Light_Floor1_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Light_Floor1_2.geometry} material={materials.LightMetal} />
        <mesh geometry={nodes.Light_Floor1_3.geometry} material={materials.Light} />
      </group>
    </group>
  );
}

useGLTF.preload("/Light Floor.glb");
