/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Light Cube.glb -o /workspaces/windgapacademy/components/CityPackModels/Light Cube.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Light Cube.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Light_Cube2_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Light_Cube2_2.geometry} material={materials.LightMetal} />
        <mesh geometry={nodes.Light_Cube2_3.geometry} material={materials.Light} />
        <mesh geometry={nodes.Light_Cube2_4.geometry} material={materials.White} />
      </group>
    </group>
  )
}

useGLTF.preload('/Light Cube.glb')
