/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Loaf Baguette.glb -o /workspaces/windgapacademy/components/CityPackModels/Loaf Baguette.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Loaf Baguette.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.loafBaguette_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.loafBaguette_1_1.geometry} material={materials.brown} />
    </group>
  );
}

useGLTF.preload("/Loaf Baguette.glb");
