/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Lollypop.glb -o /workspaces/windgapacademy/components/CityPackModels/Lollypop.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Lollypop.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lollypop_1.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.lollypop_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.lollypop_1_2.geometry} material={materials._defaultMat} />
    </group>
  );
}

useGLTF.preload("/Lollypop.glb");
