/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Long-Necked Turtle.glb -o /workspaces/windgapacademy/components/CityPackModels/Long-Necked Turtle.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Long-Necked Turtle.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={materials.turtle} />
      <mesh geometry={nodes["Plane-Mesh"].geometry} material={materials["Material.001"]} />
      <mesh geometry={nodes["Plane-Mesh_1"].geometry} material={materials["Material.002"]} />
      <mesh geometry={nodes["Plane002-Mesh"].geometry} material={materials.turtle} />
      <mesh geometry={nodes["Plane002-Mesh_1"].geometry} material={materials.Face} />
    </group>
  );
}

useGLTF.preload("/Long-Necked Turtle.glb");
