/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Lotion Bottle Small.glb -o /workspaces/windgapacademy/components/CityPackModels/Lotion Bottle Small.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Lotion Bottle Small.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.lotion_bottle_small001.geometry}
        material={materials.Solid}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      >
        <mesh geometry={nodes.lotion_bottle_small_nozzle001.geometry} material={materials.Solid} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Lotion Bottle Small.glb");
