/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Magazine.glb -o /workspaces/windgapacademy/components/CityPackModels/Magazine.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Magazine.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Magazine_Plane-Mesh"].geometry} material={materials.Black} />
      <mesh geometry={nodes["Magazine_Plane-Mesh_1"].geometry} material={materials.Skin} />
      <mesh geometry={nodes["Magazine_Plane-Mesh_2"].geometry} material={materials.Pink} />
      <mesh geometry={nodes["Magazine_Plane-Mesh_3"].geometry} material={materials.Paper} />
      <mesh geometry={nodes["Magazine_Plane-Mesh_4"].geometry} material={materials.PinkShade2} />
      <mesh geometry={nodes["Magazine_Plane-Mesh_5"].geometry} material={materials.Front} />
    </group>
  );
}

useGLTF.preload("/Magazine.glb");
