/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Mailbox.glb -o /workspaces/windgapacademy/components/CityPackModels/Mailbox.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Mailbox.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0.008, 0.242, -0.006]} rotation={[-Math.PI / 2, 0, 0]} scale={38.962}>
        <mesh geometry={nodes.Mailbox_1.geometry} material={materials.mailbox} />
        <mesh geometry={nodes.Mailbox_2.geometry} material={materials.sign} />
        <mesh geometry={nodes.Mailbox_3.geometry} material={materials.sign_shade2} />
      </group>
    </group>
  );
}

useGLTF.preload("/Mailbox.glb");
