/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Manhole cover.glb -o /workspaces/windgapacademy/components/CityPackModels/Manhole cover.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Manhole cover.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Manhole_cover_02_Cube002-Mesh'].geometry} material={materials.GrayManholecover02} />
      <mesh geometry={nodes['Manhole_cover_02_Cube002-Mesh_1'].geometry} material={materials.BlackManholecover02} />
    </group>
  )
}

useGLTF.preload('/Manhole cover.glb')
