/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Meat Raw.glb -o /workspaces/windgapacademy/components/CityPackModels/Meat Raw.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Meat Raw.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.meatRaw_1.geometry} material={materials.white} />
      <mesh geometry={nodes.meatRaw_1_1.geometry} material={materials.pink} />
    </group>
  );
}

useGLTF.preload("/Meat Raw.glb");
