/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Meat Sausage.glb -o /workspaces/windgapacademy/components/CityPackModels/Meat Sausage.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Meat Sausage.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.meatSausage.geometry} material={materials.brownDark} />
    </group>
  )
}

useGLTF.preload('/Meat Sausage.glb')
