/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Meat Tenderizer.glb -o /workspaces/windgapacademy/components/CityPackModels/Meat Tenderizer.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Meat Tenderizer.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.meatTenderizer_1.geometry} material={materials.greyLight} />
      <mesh geometry={nodes.meatTenderizer_1_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.meatTenderizer_1_2.geometry} material={materials.greyDark} />
    </group>
  );
}

useGLTF.preload("/Meat Tenderizer.glb");
