/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Meat Ribs.glb -o /workspaces/windgapacademy/components/CityPackModels/Meat Ribs.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Meat Ribs.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.meatRibs_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.meatRibs_1_1.geometry} material={materials.brownLight} />
    </group>
  )
}

useGLTF.preload('/Meat Ribs.glb')
