/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Medium Wardrobe.glb -o /workspaces/windgapacademy/components/CityPackModels/Medium Wardrobe.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Medium Wardrobe.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.MediumWardrobe1.geometry}
        material={materials.Wood1MediumWardrobe1}
        position={[-0.019, -0.04, -0.112]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[-1.056, 0.128, 0.246]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.ClosetDoorRight2_MediumWardrobe1_1.geometry}
          material={materials.Wood1ClosetDoorRight2_MediumWardrobe1}
        />
        <mesh
          geometry={nodes.ClosetDoorRight2_MediumWardrobe1_2.geometry}
          material={materials.Metal1ClosetDoorRight2_MediumWardrobe1}
        />
      </group>
      <group position={[0.956, 0.527, 0.239]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.ClosetDoorLeft1_MediumWardrobe1_1.geometry}
          material={materials.Wood1ClosetDoorLeft1_MediumWardrobe1}
        />
        <mesh
          geometry={nodes.ClosetDoorLeft1_MediumWardrobe1_2.geometry}
          material={materials.Metal1ClosetDoorLeft1_MediumWardrobe1}
        />
      </group>
      <group position={[0.318, -0.596, 0.213]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer2_MediumWardrobe1_1.geometry}
          material={materials.Metal1Drawer2_MediumWardrobe1}
        />
        <mesh
          geometry={nodes.Drawer2_MediumWardrobe1_2.geometry}
          material={materials.Wood1Drawer2_MediumWardrobe1}
        />
      </group>
      <group position={[-0.339, 0.527, 0.239]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.ClosetDoorRight1_MediumWardrobe1_1.geometry}
          material={materials.Wood1ClosetDoorRight1_MediumWardrobe1}
        />
        <mesh
          geometry={nodes.ClosetDoorRight1_MediumWardrobe1_2.geometry}
          material={materials.Metal1ClosetDoorRight1_MediumWardrobe1}
        />
      </group>
      <group position={[0.318, -0.181, 0.213]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer1_MediumWardrobe1_1.geometry}
          material={materials.Wood1Drawer1_MediumWardrobe1}
        />
        <mesh
          geometry={nodes.Drawer1_MediumWardrobe1_2.geometry}
          material={materials.Metal1Drawer1_MediumWardrobe1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Medium Wardrobe.glb");
