/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Medium Book Shelf.glb -o /workspaces/windgapacademy/components/CityPackModels/Medium Book Shelf.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Medium Book Shelf.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.MediumBookShelf1.geometry}
        material={materials.WoodMediumBookShelf1}
        position={[-0.128, 0.862, -0.026]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[-0.331, 0.182, 0.063]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.DoorRight1_MediumBookShelf1_1.geometry}
          material={materials.WoodDoorRight1_MediumBookShelf1}
        />
        <mesh
          geometry={nodes.DoorRight1_MediumBookShelf1_2.geometry}
          material={materials.MetalDoorRight1_MediumBookShelf1}
        />
      </group>
      <group position={[0.952, 0.182, 0.063]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.DoorLeft1_MediumBookShelf1_1.geometry}
          material={materials.WoodDoorLeft1_MediumBookShelf1}
        />
        <mesh
          geometry={nodes.DoorLeft1_MediumBookShelf1_2.geometry}
          material={materials.MetalDoorLeft1_MediumBookShelf1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Medium Book Shelf.glb");
