/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Message board.glb -o /workspaces/windgapacademy/components/CityPackModels/Message board.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Message board.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Message_Board.geometry} material={materials.Mat} />
    </group>
  );
}

useGLTF.preload("/Message board.glb");
