/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Mincemeat Pie.glb -o /workspaces/windgapacademy/components/CityPackModels/Mincemeat Pie.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Mincemeat Pie.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mincemeatPie_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.mincemeatPie_1_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.mincemeatPie_1_2.geometry} material={materials._defaultMat} />
    </group>
  );
}

useGLTF.preload("/Mincemeat Pie.glb");
