/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Minimalist Modern Chair.glb -o /workspaces/windgapacademy/components/CityPackModels/Minimalist Modern Chair.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Minimalist Modern Chair.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.MinimalistModernChair1_1.geometry}
          material={materials.Cloth1MinimalistModernChair1}
        />
        <mesh
          geometry={nodes.MinimalistModernChair1_2.geometry}
          material={materials.WoodMinimalistModernChair1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Minimalist Modern Chair.glb");
