/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Mirror.glb -o /workspaces/windgapacademy/components/CityPackModels/Mirror.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Mirror.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Mirror1_1.geometry} material={materials.Wood1Mirror1} />
        <mesh geometry={nodes.Mirror1_2.geometry} material={materials.Glass1Mirror1} />
      </group>
    </group>
  );
}

useGLTF.preload("/Mirror.glb");
