/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Modern Kitchen Table.glb -o /workspaces/windgapacademy/components/CityPackModels/Modern Kitchen Table.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Modern Kitchen Table.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.ModernKitchenTable1_1.geometry}
          material={materials.WoodModernKitchenTable1}
        />
        <mesh
          geometry={nodes.ModernKitchenTable1_2.geometry}
          material={materials.MarbleModernKitchenTable1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Modern Kitchen Table.glb");
