/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Monitor.glb -o /workspaces/windgapacademy/components/CityPackModels/Monitor.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Monitor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.iMac.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/Monitor.glb')
