/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Mouse.glb -o /workspaces/windgapacademy/components/CityPackModels/Mouse.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Mouse.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mouse.geometry} material={materials.Material} scale={100} />
    </group>
  )
}

useGLTF.preload('/Mouse.glb')
