/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/MS Gundam RX-78-2 with weapons.glb -o /workspaces/windgapacademy/components/CityPackModels/MS Gundam RX-78-2 with weapons.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/MS Gundam RX-78-2 with weapons.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group64581599.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1951532189.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh329101551.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh329101551_1.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh329101551_2.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh329101551_3.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh329101551_4.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh329101551_5.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1485409560.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1485409560_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1516597679.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1516597679_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1516597679_2.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1516597679_3.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh515072761.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh515072761_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh95713692.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh95713692_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh95713692_2.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh95713692_3.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1886660860.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1886660860_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1886660860_2.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1886660860_3.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1886660860_4.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1300186925.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1300186925_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1300186925_2.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1300186925_3.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh604555286.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh604555286_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1709387099.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1709387099_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1709387099_2.geometry} material={materials.mat17} />
    </group>
  );
}

useGLTF.preload("/MS Gundam RX-78-2 with weapons.glb");
