/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Mugs.glb -o /workspaces/windgapacademy/components/CityPackModels/Mugs.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Mugs.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder003.geometry} material={materials["07___Default"]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials["07___Default"]} />
      <mesh geometry={nodes.Cylinder001_1.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Cylinder001_1_1.geometry} material={materials["01___Default"]} />
      <mesh geometry={nodes.Arc001_1.geometry} material={materials["01___Default-2"]} />
      <mesh geometry={nodes.Arc001_1_1.geometry} material={materials["02___Default-2"]} />
      <mesh geometry={nodes.Cylinder002_1.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Cylinder002_1_1.geometry} material={materials["08___Default"]} />
      <mesh geometry={nodes.Arc002_1.geometry} material={materials["08___Default-2"]} />
      <mesh geometry={nodes.Arc002_1_1.geometry} material={materials["02___Default-2"]} />
    </group>
  );
}

useGLTF.preload("/Mugs.glb");
