/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Mushroom Half.glb -o /workspaces/windgapacademy/components/CityPackModels/Mushroom Half.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Mushroom Half.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mushroomHalf_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.mushroomHalf_1_1.geometry} material={materials.brownLight} />
    </group>
  );
}

useGLTF.preload("/Mushroom Half.glb");
