/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Mushroom.glb -o /workspaces/windgapacademy/components/CityPackModels/Mushroom.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Mushroom.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mushroom_Common.geometry} material={materials.Mushrooms} />
    </group>
  );
}

useGLTF.preload("/Mushroom.glb");
