/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Mushroom Laetiporus.glb -o /workspaces/windgapacademy/components/CityPackModels/Mushroom Laetiporus.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Mushroom Laetiporus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mushroom_Laetiporus.geometry} material={materials.Mushrooms} />
    </group>
  )
}

useGLTF.preload('/Mushroom Laetiporus.glb')
