/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Mussel Open.glb -o /workspaces/windgapacademy/components/CityPackModels/Mussel Open.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Mussel Open.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.musselOpen_1.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.musselOpen_1_1.geometry} material={materials.brownLight} />
    </group>
  )
}

useGLTF.preload('/Mussel Open.glb')
