/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Night Stand.glb -o /workspaces/windgapacademy/components/CityPackModels/Night Stand.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Night Stand.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.NightStand_2_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.NightStand_2_2.geometry} material={materials.Metal} />
      </group>
    </group>
  );
}

useGLTF.preload("/Night Stand.glb");
