/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Office Chair.glb -o /workspaces/windgapacademy/components/CityPackModels/Office Chair.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Office Chair.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.OfficeChair_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.OfficeChair_2.geometry} material={materials.Black} />
        <mesh geometry={nodes.OfficeChair_3.geometry} material={materials.Chair} />
      </group>
    </group>
  );
}

useGLTF.preload("/Office Chair.glb");
