/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Office Phone.glb -o /workspaces/windgapacademy/components/CityPackModels/Office Phone.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Office Phone.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.46, -1.577, -0.973]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Phone_Body_1.geometry} material={materials['Light grey']} />
        <mesh geometry={nodes.Phone_Body_2.geometry} material={materials['Grey Plastic']} />
        <mesh geometry={nodes.Phone_Body_3.geometry} material={materials.Screen} />
        <mesh geometry={nodes.Phone_Body_4.geometry} material={materials['Dark Grey Plastic']} />
        <mesh geometry={nodes.Handle.geometry} material={materials['Dark Grey Plastic']} position={[-0.016, -0.008, 0.02]} rotation={[-0.374, 0, Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Office Phone.glb')
