/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Open Base Cabinet.glb -o /workspaces/windgapacademy/components/CityPackModels/Open Base Cabinet.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Open Base Cabinet.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.OpenBaseCabinet1_1.geometry} material={materials.WoodOpenBaseCabinet1} />
        <mesh geometry={nodes.OpenBaseCabinet1_2.geometry} material={materials.MarbleOpenBaseCabinet1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Open Base Cabinet.glb')
