/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Orange.glb -o /workspaces/windgapacademy/components/CityPackModels/Orange.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Orange.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.orange_1.geometry} material={materials.orange} />
      <mesh geometry={nodes.orange_1_1.geometry} material={materials.green} />
    </group>
  );
}

useGLTF.preload("/Orange.glb");
