/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Ottoman Coffe Table.glb -o /workspaces/windgapacademy/components/CityPackModels/Ottoman Coffe Table.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Ottoman Coffe Table.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.OttomanCoffeTable1_1.geometry}
          material={materials.WoodOttomanCoffeTable1}
        />
        <mesh
          geometry={nodes.OttomanCoffeTable1_2.geometry}
          material={materials.PadOttomanCoffeTable1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Ottoman Coffe Table.glb");
