/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Oven Solo.glb -o /workspaces/windgapacademy/components/CityPackModels/Oven Solo.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Oven Solo.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.OvenSolo1.geometry}
        material={materials.SteelOvenSolo1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[-0.07, -0.205, 0.23]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Door1OvenSolo1_1.geometry} material={materials.SteelDoor1OvenSolo1} />
        <mesh geometry={nodes.Door1OvenSolo1_2.geometry} material={materials.GlassDoor1OvenSolo1} />
      </group>
      <mesh
        geometry={nodes.OvenGrill1OvenSolo1.geometry}
        material={materials.SteelOvenGrill1OvenSolo1}
        position={[-0.065, 0.018, -0.006]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Button1OvenSolo1.geometry}
        material={materials.MetalButton1OvenSolo1}
        position={[0.312, 0.12, 0.233]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Button2OvenSolo1.geometry}
        material={materials.MetalButton2OvenSolo1}
        position={[0.312, -0.001, 0.233]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Button3OvenSolo1.geometry}
        material={materials.MetalButton3OvenSolo1}
        position={[0.312, -0.122, 0.233]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Oven Solo.glb");
