/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Painting Canvas.glb -o /workspaces/windgapacademy/components/CityPackModels/Painting Canvas.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Painting Canvas.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 3, 0, 0]} scale={[48.689, 3.023, 59.53]}>
        <mesh
          geometry={nodes.PaintingCanvas1_1.geometry}
          material={materials.Wood1PaintingCanvas1}
        />
        <mesh
          geometry={nodes.PaintingCanvas1_2.geometry}
          material={materials.Canvas1PaintingCanvas1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Painting Canvas.glb");
