/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pan.glb -o /workspaces/windgapacademy/components/CityPackModels/Pan.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pan.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pan_1.geometry} material={materials.greyDark} />
      <mesh geometry={nodes.pan_1_1.geometry} material={materials._defaultMat} />
    </group>
  );
}

useGLTF.preload("/Pan.glb");
