/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Parasol.glb -o /workspaces/windgapacademy/components/CityPackModels/Parasol.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Parasol.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Parasol1_1.geometry} material={materials.WoodParasol1} />
      <mesh geometry={nodes.Parasol1_2.geometry} material={materials.Parasol1} />
    </group>
  );
}

useGLTF.preload("/Parasol.glb");
