/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pear Half.glb -o /workspaces/windgapacademy/components/CityPackModels/Pear Half.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pear Half.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pearHalf_1.geometry} material={materials.green} />
      <mesh geometry={nodes.pearHalf_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.pearHalf_1_2.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.pearHalf_1_3.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.pearHalf_1_4.geometry} material={materials._defaultMat} />
    </group>
  );
}

useGLTF.preload("/Pear Half.glb");
