/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pebble Square-2YtLzwgsWp.glb -o /workspaces/windgapacademy/components/CityPackModels/Pebble Square-2YtLzwgsWp.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pebble Square-2YtLzwgsWp.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Square_3.geometry} material={materials.PathRocks} />
    </group>
  );
}

useGLTF.preload("/Pebble Square-2YtLzwgsWp.glb");
