/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pebble Round-kAMfq1uJUY.glb -o /workspaces/windgapacademy/components/CityPackModels/Pebble Round-kAMfq1uJUY.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pebble Round-kAMfq1uJUY.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Round_4.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Pebble Round-kAMfq1uJUY.glb')
