/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pebble Square-Mm4RMgwNO8.glb -o /workspaces/windgapacademy/components/CityPackModels/Pebble Square-Mm4RMgwNO8.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pebble Square-Mm4RMgwNO8.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Square_2.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Pebble Square-Mm4RMgwNO8.glb')
