/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pebble Square.glb -o /workspaces/windgapacademy/components/CityPackModels/Pebble Square.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pebble Square.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pebble_Square_4.geometry} material={materials.PathRocks} />
    </group>
  );
}

useGLTF.preload("/Pebble Square.glb");
