/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pencil.glb -o /workspaces/windgapacademy/components/CityPackModels/Pencil.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pencil.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Pencil1_1.geometry} material={materials.Ferrule1Pencil1} />
        <mesh geometry={nodes.Pencil1_2.geometry} material={materials.Eraser1Pencil1} />
        <mesh geometry={nodes.Pencil1_3.geometry} material={materials.Wood1Pencil1} />
        <mesh geometry={nodes.Pencil1_4.geometry} material={materials.Lead1Pencil1} />
      </group>
    </group>
  );
}

useGLTF.preload("/Pencil.glb");
