/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pens.glb -o /workspaces/windgapacademy/components/CityPackModels/Pens.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pens.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box006.geometry} material={materials["08___Default"]} />
      <mesh geometry={nodes.Box007.geometry} material={materials["03___Default"]} />
      <mesh geometry={nodes.Object003.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box008.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box009.geometry} material={materials["09___Default"]} />
      <mesh geometry={nodes.Box010.geometry} material={materials["07___Default"]} />
      <mesh geometry={nodes.Object004.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Cylinder006_1.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Cylinder006_1_1.geometry} material={materials["08___Default"]} />
      <mesh geometry={nodes.Cylinder007_1.geometry} material={materials["03___Default"]} />
      <mesh geometry={nodes.Cylinder007_1_1.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Cylinder008_1.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Cylinder008_1_1.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Cylinder009_1.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Cylinder009_1_1.geometry} material={materials["09___Default"]} />
      <mesh geometry={nodes.Cylinder010_1.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Cylinder010_1_1.geometry} material={materials["07___Default"]} />
    </group>
  );
}

useGLTF.preload("/Pens.glb");
