/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pepper Mill.glb -o /workspaces/windgapacademy/components/CityPackModels/Pepper Mill.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pepper Mill.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pepperMill.geometry} material={materials.brownLight} />
    </group>
  );
}

useGLTF.preload("/Pepper Mill.glb");
