/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pie.glb -o /workspaces/windgapacademy/components/CityPackModels/Pie.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pie.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pie_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.pie_1_1.geometry} material={materials.greyLight} />
      <mesh geometry={nodes.pie_1_2.geometry} material={materials.brown} />
      <mesh geometry={nodes.pie_1_3.geometry} material={materials.brownLight} />
    </group>
  );
}

useGLTF.preload("/Pie.glb");
