/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pillar.glb -o /workspaces/windgapacademy/components/CityPackModels/Pillar.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pillar.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pillar1.geometry} material={materials.Pillar1} />
    </group>
  );
}

useGLTF.preload("/Pillar.glb");
