/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pine.glb -o /workspaces/windgapacademy/components/CityPackModels/Pine.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pine.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pine_5_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.Pine_5_2.geometry} material={materials.Leaves_Pine} />
    </group>
  );
}

useGLTF.preload("/Pine.glb");
