/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pine-79gmlLnweB.glb -o /workspaces/windgapacademy/components/CityPackModels/Pine-79gmlLnweB.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pine-79gmlLnweB.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pine_4_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.Pine_4_2.geometry} material={materials.Leaves_Pine} />
    </group>
  )
}

useGLTF.preload('/Pine-79gmlLnweB.glb')
