/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pineapple.glb -o /workspaces/windgapacademy/components/CityPackModels/Pineapple.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pineapple.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pineapple_1.geometry} material={materials.yellow} />
      <mesh geometry={nodes.pineapple_1_1.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('/Pineapple.glb')
