/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pine-rfnxJv0Rqa.glb -o /workspaces/windgapacademy/components/CityPackModels/Pine-rfnxJv0Rqa.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pine-rfnxJv0Rqa.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pine_1_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.Pine_1_2.geometry} material={materials.Leaves_Pine} />
    </group>
  )
}

useGLTF.preload('/Pine-rfnxJv0Rqa.glb')
