/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pizza.glb -o /workspaces/windgapacademy/components/CityPackModels/Pizza.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pizza.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.slice1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.slice1_1_1.geometry} material={materials.yellow} />
      <mesh geometry={nodes.slice1_1_2.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice1_1_3.geometry} material={materials.red} />
      <mesh geometry={nodes.slice1_1_4.geometry} material={materials.green} />
      <mesh geometry={nodes.slice2_1.geometry} material={materials.green} />
      <mesh geometry={nodes.slice2_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.slice2_1_2.geometry} material={materials.yellow} />
      <mesh geometry={nodes.slice2_1_3.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice2_1_4.geometry} material={materials.red} />
      <mesh geometry={nodes.slice3_1.geometry} material={materials.green} />
      <mesh geometry={nodes.slice3_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.slice3_1_2.geometry} material={materials.yellow} />
      <mesh geometry={nodes.slice3_1_3.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice3_1_4.geometry} material={materials.red} />
      <mesh geometry={nodes.slice4_1.geometry} material={materials.green} />
      <mesh geometry={nodes.slice4_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.slice4_1_2.geometry} material={materials.yellow} />
      <mesh geometry={nodes.slice4_1_3.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice4_1_4.geometry} material={materials.red} />
      <mesh geometry={nodes.slice5_1.geometry} material={materials.green} />
      <mesh geometry={nodes.slice5_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.slice5_1_2.geometry} material={materials.yellow} />
      <mesh geometry={nodes.slice5_1_3.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice5_1_4.geometry} material={materials.red} />
      <mesh geometry={nodes.slice6_1.geometry} material={materials.green} />
      <mesh geometry={nodes.slice6_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.slice6_1_2.geometry} material={materials.yellow} />
      <mesh geometry={nodes.slice6_1_3.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice6_1_4.geometry} material={materials.red} />
      <mesh geometry={nodes.slice7_1.geometry} material={materials.green} />
      <mesh geometry={nodes.slice7_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.slice7_1_2.geometry} material={materials.yellow} />
      <mesh geometry={nodes.slice7_1_3.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice7_1_4.geometry} material={materials.red} />
      <mesh geometry={nodes.slice8_1.geometry} material={materials.green} />
      <mesh geometry={nodes.slice8_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.slice8_1_2.geometry} material={materials.yellow} />
      <mesh geometry={nodes.slice8_1_3.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.slice8_1_4.geometry} material={materials.red} />
    </group>
  );
}

useGLTF.preload("/Pizza.glb");
