/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pizza Corner.glb -o /workspaces/windgapacademy/components/CityPackModels/Pizza Corner.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pizza Corner.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0.004, 1.516, 0]} rotation={[Math.PI / 2, 0, 0]} scale={-60}>
        <mesh geometry={nodes.PizzaCorner_1.geometry} material={materials.brick_shadeGreen} />
        <mesh geometry={nodes.PizzaCorner_2.geometry} material={materials.concrete} />
        <mesh geometry={nodes.PizzaCorner_3.geometry} material={materials.window_frame} />
        <mesh geometry={nodes.PizzaCorner_4.geometry} material={materials.window_glass} />
        <mesh geometry={nodes.PizzaCorner_5.geometry} material={materials.door_white} />
        <mesh geometry={nodes.PizzaCorner_6.geometry} material={materials.sandstone} />
        <mesh geometry={nodes.PizzaCorner_7.geometry} material={materials.brick_shadeGreen2} />
        <mesh geometry={nodes.PizzaCorner_8.geometry} material={materials.white} />
        <mesh geometry={nodes.PizzaCorner_9.geometry} material={materials.red} />
      </group>
    </group>
  );
}

useGLTF.preload("/Pizza Corner.glb");
