/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pizza Cutter.glb -o /workspaces/windgapacademy/components/CityPackModels/Pizza Cutter.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pizza Cutter.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pizzaCutter_1.geometry} material={materials.white} />
      <mesh geometry={nodes.pizzaCutter_1_1.geometry} material={materials.greyLight} />
      <mesh geometry={nodes.pizzaCutter_1_2.geometry} material={materials.brown} />
      <mesh geometry={nodes.pizzaCutter_1_3.geometry} material={materials._defaultMat} />
    </group>
  );
}

useGLTF.preload("/Pizza Cutter.glb");
