/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Plant - White Pot.glb -o /workspaces/windgapacademy/components/CityPackModels/Plant - White Pot.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Plant - White Pot.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group24448074.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1406455588.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1377145234.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1699085095.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group722357104.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1507777984.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group285410933.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1278045090.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1987077651.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group560799048.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1308825903.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1417853301.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group172818934.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group2053840647.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1647754183.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1377232627.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1781696643.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group476784665.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group103419857.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1025492697.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1989238829.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group31856083.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group525605584.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group714662036.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1885116500.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1885116500_1.geometry} material={materials.mat20} />
    </group>
  );
}

useGLTF.preload("/Plant - White Pot.glb");
