/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Planter & Bushes.glb -o /workspaces/windgapacademy/components/CityPackModels/Planter & Bushes.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Planter & Bushes.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.077, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.PlanterBushes_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.PlanterBushes_2.geometry} material={materials.dirt} />
        <mesh geometry={nodes.PlanterBushes_3.geometry} material={materials.plant} />
      </group>
    </group>
  );
}

useGLTF.preload("/Planter & Bushes.glb");
