/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Plant.glb -o /workspaces/windgapacademy/components/CityPackModels/Plant.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Plant.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plant_1.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/Plant.glb')
