/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Plant Big-MbhbP7JrTI.glb -o /workspaces/windgapacademy/components/CityPackModels/Plant Big-MbhbP7JrTI.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Plant Big-MbhbP7JrTI.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plant_1_Big.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/Plant Big-MbhbP7JrTI.glb')
