/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Plastic Cup.glb -o /workspaces/windgapacademy/components/CityPackModels/Plastic Cup.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Plastic Cup.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PlasticCup1.geometry} material={materials.PlasticCup1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Plastic Cup.glb')
