/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pool Table.glb -o /workspaces/windgapacademy/components/CityPackModels/Pool Table.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pool Table.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh1_Group2_Group1_Model.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh3_Group3_Group1_Model.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh5_Group4_Group1_Model.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh7_Group5_Group1_Model.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh46_Group1_Model.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh9_patte1_Group1_Model_1.geometry} material={materials.Color_M09} />
      <mesh
        geometry={nodes.Mesh9_patte1_Group1_Model_1_1.geometry}
        material={materials.Color_M00}
      />
      <mesh geometry={nodes.Mesh18_patte2_Group1_Model_1.geometry} material={materials.Color_M00} />
      <mesh
        geometry={nodes.Mesh18_patte2_Group1_Model_1_1.geometry}
        material={materials.Color_M09}
      />
      <mesh geometry={nodes.Mesh27_patte3_Group1_Model_1.geometry} material={materials.Color_M00} />
      <mesh
        geometry={nodes.Mesh27_patte3_Group1_Model_1_1.geometry}
        material={materials.Color_M09}
      />
      <mesh geometry={nodes.Mesh36_patte4_Group1_Model_1.geometry} material={materials.Color_M00} />
      <mesh
        geometry={nodes.Mesh36_patte4_Group1_Model_1_1.geometry}
        material={materials.Color_M09}
      />
      <mesh geometry={nodes.Mesh45_Group1_Model_1.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh45_Group1_Model_1_1.geometry} material={materials.Color_K05} />
      <mesh geometry={nodes.Mesh47_Group1_Model_1.geometry} material={materials.Color_L21} />
      <mesh geometry={nodes.Mesh47_Group1_Model_1_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh48_Group1_Model_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh48_Group1_Model_1_1.geometry} material={materials.Color_B01} />
      <mesh geometry={nodes.Mesh48_Group1_Model_1_2.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh49_Group1_Model_1.geometry} material={materials.Color_B01} />
      <mesh geometry={nodes.Mesh49_Group1_Model_1_1.geometry} material={materials.FrontColor} />
      <mesh geometry={nodes.Mesh50_Group1_Model_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh50_Group1_Model_1_1.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh50_Group1_Model_1_2.geometry} material={materials.Color_A06} />
      <mesh geometry={nodes.Mesh51_Group1_Model_1.geometry} material={materials.Color_I01} />
      <mesh geometry={nodes.Mesh51_Group1_Model_1_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh52_Group1_Model_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh52_Group1_Model_1_1.geometry} material={materials.Color_J16} />
      <mesh geometry={nodes.Mesh52_Group1_Model_1_2.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh53_Group1_Model_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh53_Group1_Model_1_1.geometry} material={materials.FrontColor} />
      <mesh geometry={nodes.Mesh54_Group1_Model_1.geometry} material={materials.FrontColor} />
      <mesh geometry={nodes.Mesh54_Group1_Model_1_1.geometry} material={materials.Color_A06} />
      <mesh geometry={nodes.Mesh55_Group1_Model_1.geometry} material={materials.Color_G17} />
      <mesh geometry={nodes.Mesh55_Group1_Model_1_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh56_Group1_Model_1.geometry} material={materials.Color_L21} />
      <mesh geometry={nodes.Mesh56_Group1_Model_1_1.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh56_Group1_Model_1_2.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh57_Group1_Model_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh57_Group1_Model_1_1.geometry} material={materials.Color_J16} />
      <mesh geometry={nodes.Mesh58_Group1_Model_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh58_Group1_Model_1_1.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh58_Group1_Model_1_2.geometry} material={materials.Color_D01} />
      <mesh geometry={nodes.Mesh59_Group1_Model_1.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh59_Group1_Model_1_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh59_Group1_Model_1_2.geometry} material={materials.Color_G17} />
      <mesh geometry={nodes.Mesh60_Group1_Model_1.geometry} material={materials.Color_D01} />
      <mesh geometry={nodes.Mesh60_Group1_Model_1_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh61_Group1_Model_1.geometry} material={materials._Color_009_1} />
      <mesh geometry={nodes.Mesh61_Group1_Model_1_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh62_Group1_Model_1.geometry} material={materials.Color_M09} />
      <mesh geometry={nodes.Mesh62_Group1_Model_1_1.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.Mesh62_Group1_Model_1_2.geometry} material={materials.Color_I01} />
    </group>
  );
}

useGLTF.preload("/Pool Table.glb");
