/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Popsicle Chocolate.glb -o /workspaces/windgapacademy/components/CityPackModels/Popsicle Chocolate.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Popsicle Chocolate.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.popsicleChocolate_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.popsicleChocolate_1_1.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.popsicleChocolate_1_2.geometry} material={materials.brownDark} />
    </group>
  );
}

useGLTF.preload("/Popsicle Chocolate.glb");
