/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pot Stew.glb -o /workspaces/windgapacademy/components/CityPackModels/Pot Stew.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pot Stew.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.potStew_1.geometry} material={materials.greyDark} />
      <mesh geometry={nodes.potStew_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.potStew_1_2.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.potStew_1_3.geometry} material={materials.yellow} />
      <mesh geometry={nodes.potStew_1_4.geometry} material={materials.orange} />
      <mesh geometry={nodes.potStew_1_5.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/Pot Stew.glb')
