/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pot.glb -o /workspaces/windgapacademy/components/CityPackModels/Pot.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Pot.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.075, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Lid1Pot1_1.geometry} material={materials.GlassLid1Pot1} />
        <mesh geometry={nodes.Lid1Pot1_2.geometry} material={materials.PlasticLid1Pot1} />
      </group>
      <mesh
        geometry={nodes.Pot1.geometry}
        material={materials.SteelPot1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Pot.glb");
