/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Potted Plant.glb -o /workspaces/windgapacademy/components/CityPackModels/Potted Plant.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Potted Plant.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Potted_Plant000.geometry} material={materials.Material} scale={100} />
    </group>
  );
}

useGLTF.preload("/Potted Plant.glb");
