/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Power Box.glb -o /workspaces/windgapacademy/components/CityPackModels/Power Box.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Power Box.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.134, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={51.03}>
        <mesh geometry={nodes.PowerBox_1.geometry} material={materials.metal_shade1} />
        <mesh geometry={nodes.PowerBox_2.geometry} material={materials.metal_shade2} />
        <mesh geometry={nodes.PowerBox_3.geometry} material={materials.yellow_sticker} />
        <mesh geometry={nodes.PowerBox_4.geometry} material={materials.black_sticker} />
      </group>
    </group>
  );
}

useGLTF.preload("/Power Box.glb");
