/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Printer.glb -o /workspaces/windgapacademy/components/CityPackModels/Printer.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Printer.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Printer.geometry} material={materials.Material} scale={100} />
    </group>
  );
}

useGLTF.preload("/Printer.glb");
