/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Protein Powder.glb -o /workspaces/windgapacademy/components/CityPackModels/Protein Powder.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Protein Powder.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Protein1_1.geometry} material={materials.Plastic1Protein1} />
        <mesh geometry={nodes.Protein1_2.geometry} material={materials.Lid1Protein1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Protein Powder.glb')
