/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Pumpkin Basic.glb -o /workspaces/windgapacademy/components/CityPackModels/Pumpkin Basic.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pumpkin Basic.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pumpkinBasic_1.geometry} material={materials.orange} />
      <mesh geometry={nodes.pumpkinBasic_1_1.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('/Pumpkin Basic.glb')
