/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Punching Bag.glb -o /workspaces/windgapacademy/components/CityPackModels/Punching Bag.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Punching Bag.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.PunchingBag1_1.geometry} material={materials.Bag1PunchingBag1} />
        <mesh geometry={nodes.PunchingBag1_2.geometry} material={materials.Base1PunchingBag1} />
        <mesh geometry={nodes.PunchingBag1_3.geometry} material={materials.Bar1PunchingBag1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Punching Bag.glb')
