/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/RB Blank.glb -o /workspaces/windgapacademy/components/CityPackModels/RB Blank.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/RB Blank.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.065, 1.665, 0.544]} rotation={[-Math.PI / 2, 0, 0]} scale={60}>
        <mesh geometry={nodes.RBBlank_1.geometry} material={materials.window_frame} />
        <mesh geometry={nodes.RBBlank_2.geometry} material={materials.brick_shade1} />
        <mesh geometry={nodes.RBBlank_3.geometry} material={materials.window_glass} />
        <mesh geometry={nodes.RBBlank_4.geometry} material={materials.sandstone} />
        <mesh geometry={nodes.RBBlank_5.geometry} material={materials.brick_shade2} />
        <mesh geometry={nodes.RBBlank_6.geometry} material={materials.concrete} />
      </group>
    </group>
  );
}

useGLTF.preload("/RB Blank.glb");
