/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Rock-p5J3xclZRY.glb -o /workspaces/windgapacademy/components/CityPackModels/Rock-p5J3xclZRY.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Rock-p5J3xclZRY.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock2.geometry} material={materials.Rock2} />
    </group>
  );
}

useGLTF.preload("/Rock-p5J3xclZRY.glb");
