/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Rock Medium.glb -o /workspaces/windgapacademy/components/CityPackModels/Rock Medium.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Rock Medium.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_Medium_2.geometry} material={materials.Rocks} />
    </group>
  );
}

useGLTF.preload("/Rock Medium.glb");
