/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Rock-fM90QFMNtS.glb -o /workspaces/windgapacademy/components/CityPackModels/Rock-fM90QFMNtS.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock-fM90QFMNtS.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock4.geometry} material={materials.Rock4} />
    </group>
  )
}

useGLTF.preload('/Rock-fM90QFMNtS.glb')
