/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Rock Medium-JQxF95498B.glb -o /workspaces/windgapacademy/components/CityPackModels/Rock Medium-JQxF95498B.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock Medium-JQxF95498B.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_Medium_3.geometry} material={materials.Rocks} />
    </group>
  )
}

useGLTF.preload('/Rock Medium-JQxF95498B.glb')
