/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Rock Path Square Wide.glb -o /workspaces/windgapacademy/components/CityPackModels/Rock Path Square Wide.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Rock Path Square Wide.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Square_Wide.geometry} material={materials.PathRocks} />
    </group>
  );
}

useGLTF.preload("/Rock Path Square Wide.glb");
