/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Rock-UkxWNmiFFj.glb -o /workspaces/windgapacademy/components/CityPackModels/Rock-UkxWNmiFFj.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock-UkxWNmiFFj.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock1.geometry} material={materials.Rock1} />
    </group>
  )
}

useGLTF.preload('/Rock-UkxWNmiFFj.glb')
