/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Rock Path Round Thin.glb -o /workspaces/windgapacademy/components/CityPackModels/Rock Path Round Thin.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock Path Round Thin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RockPath_Round_Thin.geometry} material={materials.PathRocks} />
    </group>
  )
}

useGLTF.preload('/Rock Path Round Thin.glb')
