/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Rock band poster.glb -o /workspaces/windgapacademy/components/CityPackModels/Rock band poster.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rock band poster.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh'].geometry} material={materials['1A1A1A']} />
      <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_1'].geometry} material={materials.DD9944} />
      <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_2'].geometry} material={materials.F44336} />
      <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_3'].geometry} material={materials.FFFFFF} />
      <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_4'].geometry} material={materials['039BE5']} />
      <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_5'].geometry} material={materials['795548']} />
      <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_6'].geometry} material={materials['00BCD4']} />
      <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_7'].geometry} material={materials.FFCC88} />
      <mesh geometry={nodes['Rock_Band_Poster_Plane002-Mesh_8'].geometry} material={materials['009688']} />
    </group>
  )
}

useGLTF.preload('/Rock band poster.glb')
