/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Roof Exit.glb -o /workspaces/windgapacademy/components/CityPackModels/Roof Exit.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Roof Exit.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.016, 0.313, -0.234]} rotation={[-Math.PI / 2, 0, 0]} scale={22}>
        <mesh geometry={nodes.RoofExit_1.geometry} material={materials.sandstone} />
        <mesh geometry={nodes.RoofExit_2.geometry} material={materials.brick_shade1} />
        <mesh geometry={nodes.RoofExit_3.geometry} material={materials.wood} />
        <mesh geometry={nodes.RoofExit_4.geometry} material={materials.door} />
        <mesh geometry={nodes.RoofExit_5.geometry} material={materials.brick_shade2} />
      </group>
    </group>
  );
}

useGLTF.preload("/Roof Exit.glb");
