/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Round Brush.glb -o /workspaces/windgapacademy/components/CityPackModels/Round Brush.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Round Brush.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.RoundBrush1_1.geometry} material={materials.Wood1RoundBrush1} />
        <mesh geometry={nodes.RoundBrush1_2.geometry} material={materials.Bristles1RoundBrush1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Round Brush.glb')
