/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Rug Round.glb -o /workspaces/windgapacademy/components/CityPackModels/Rug Round.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rug Round.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.rugRound_2.geometry} material={materials.carpet} />
      <mesh geometry={nodes.rugRound_2_1.geometry} material={materials.carpetDarker} />
      <mesh geometry={nodes.rugRound_3.geometry} material={materials.carpetDarker} />
      <mesh geometry={nodes.rugRound_3_1.geometry} material={materials.carpet} />
    </group>
  )
}

useGLTF.preload('/Rug Round.glb')
