/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Salad.glb -o /workspaces/windgapacademy/components/CityPackModels/Salad.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Salad.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.salad_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.salad_1_1.geometry} material={materials.green} />
      <mesh geometry={nodes.salad_1_2.geometry} material={materials.red} />
      <mesh geometry={nodes.salad_1_3.geometry} material={materials.greenDark} />
    </group>
  );
}

useGLTF.preload("/Salad.glb");
