/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Sauce Pan.glb -o /workspaces/windgapacademy/components/CityPackModels/Sauce Pan.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Sauce Pan.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.064, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Lid1SaucePan1_1.geometry} material={materials.GlassLid1SaucePan1} />
        <mesh geometry={nodes.Lid1SaucePan1_2.geometry} material={materials.PlasticLid1SaucePan1} />
      </group>
      <mesh
        geometry={nodes.SaucePan1.geometry}
        material={materials.SteelSaucePan1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Sauce Pan.glb");
