/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Sausage.glb -o /workspaces/windgapacademy/components/CityPackModels/Sausage.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Sausage.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sausage.geometry} material={materials.brownLight} />
    </group>
  );
}

useGLTF.preload("/Sausage.glb");
