/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Shaker Salt.glb -o /workspaces/windgapacademy/components/CityPackModels/Shaker Salt.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Shaker Salt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.shakerSalt_1.geometry} material={materials.greyDark} />
      <mesh geometry={nodes.shakerSalt_1_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.shakerSalt_1_2.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/Shaker Salt.glb')
