/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Shelf.glb -o /workspaces/windgapacademy/components/CityPackModels/Shelf.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Shelf.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group252943910.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group530080379.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group921275821.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group431821521.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group659176328.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1808194429.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group174979704.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group890327909.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1082046218.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group555946532.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1813242810.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1750653242.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group807391238.geometry} material={materials.mat23} />
    </group>
  )
}

useGLTF.preload('/Shelf.glb')
