/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Single Door Base Cabinet-DKfKjxQyWX.glb -o /workspaces/windgapacademy/components/CityPackModels/Single Door Base Cabinet-DKfKjxQyWX.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Single Door Base Cabinet-DKfKjxQyWX.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.SingleDoorbaseCabinetWDrawer1_1.geometry}
          material={materials.WoodSingleDoorbaseCabinetWDrawer1}
        />
        <mesh
          geometry={nodes.SingleDoorbaseCabinetWDrawer1_2.geometry}
          material={materials.MarbleSingleDoorbaseCabinetWDrawer1}
        />
      </group>
      <group position={[-0.208, -0.032, 0.295]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Door1SingleDoorbaseCabinetWDrawer1_1.geometry}
          material={materials.WoodDoor1SingleDoorbaseCabinetWDrawer1}
        />
        <mesh
          geometry={nodes.Door1SingleDoorbaseCabinetWDrawer1_2.geometry}
          material={materials.MetalDoor1SingleDoorbaseCabinetWDrawer1}
        />
      </group>
      <group position={[0, 0.333, 0.233]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer1SingleDoorbaseCabinetWDrawer1_1.geometry}
          material={materials.WoodDrawer1SingleDoorbaseCabinetWDrawer1}
        />
        <mesh
          geometry={nodes.Drawer1SingleDoorbaseCabinetWDrawer1_2.geometry}
          material={materials.MetalDrawer1SingleDoorbaseCabinetWDrawer1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Single Door Base Cabinet-DKfKjxQyWX.glb");
