/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Single Door Base Cabinet.glb -o /workspaces/windgapacademy/components/CityPackModels/Single Door Base Cabinet.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Single Door Base Cabinet.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.SingleDoorBaseCabinet1_1.geometry}
          material={materials.WoodSingleDoorBaseCabinet1}
        />
        <mesh
          geometry={nodes.SingleDoorBaseCabinet1_2.geometry}
          material={materials.MarbleSingleDoorBaseCabinet1}
        />
      </group>
      <group position={[-0.208, 0.055, 0.295]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Door1SingleDoorbaseCabinet1_1.geometry}
          material={materials.WoodDoor1SingleDoorbaseCabinet1}
        />
        <mesh
          geometry={nodes.Door1SingleDoorbaseCabinet1_2.geometry}
          material={materials.MetalDoor1SingleDoorbaseCabinet1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Single Door Base Cabinet.glb");
