/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Single Door Tall Cabine.glb -o /workspaces/windgapacademy/components/CityPackModels/Single Door Tall Cabine.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Single Door Tall Cabine.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.SingleDoorTallCabinet1.geometry}
        material={materials.WoodSingleDoorTallCabinet1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[-0.22, -0.092, 0.309]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Door1SingleDoorTallCabinet1_1.geometry}
          material={materials.WoodDoor1SingleDoorTallCabinet1}
        />
        <mesh
          geometry={nodes.Door1SingleDoorTallCabinet1_2.geometry}
          material={materials.MetalDoor1SingleDoorTallCabinet1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Single Door Tall Cabine.glb");
