/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Single Door Upper Cabinet.glb -o /workspaces/windgapacademy/components/CityPackModels/Single Door Upper Cabinet.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Single Door Upper Cabinet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SingleDoorUpperCabinet1.geometry} material={materials.WoodSingleDoorUpperCabinet1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <group position={[-0.228, -0.009, 0.178]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Door1SingleDoorUpperCabinet1_1.geometry} material={materials.WoodDoor1SingleDoorUpperCabinet1} />
        <mesh geometry={nodes.Door1SingleDoorUpperCabinet1_2.geometry} material={materials.MetalDoor1SingleDoorUpperCabinet1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Single Door Upper Cabinet.glb')
