/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Single Bed.glb -o /workspaces/windgapacademy/components/CityPackModels/Single Bed.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Single Bed.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.335, 0.009, -1.08]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.SingleBed1_1.geometry} material={materials.Mattress1_SingleBed1} />
        <mesh geometry={nodes.SingleBed1_2.geometry} material={materials.Wood1SingleBed1} />
      </group>
      <mesh
        geometry={nodes.Blanket1_SingleBed1.geometry}
        material={materials.Cloth1Blanket1_SingleBed1}
        position={[-0.338, -0.175, 0.365]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Pillow1_SingleBed1.geometry}
        material={materials.Pillow1_SingleBed1}
        position={[-0.324, 0.077, -1.123]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Single Bed.glb");
