/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Sink Kitchen Cabinet.glb -o /workspaces/windgapacademy/components/CityPackModels/Sink Kitchen Cabinet.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Sink Kitchen Cabinet.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.MarbleSinkKitchenCabinet1_1.geometry}
          material={materials.WoodMarbleSinkKitchenCabinet1}
        />
        <mesh
          geometry={nodes.MarbleSinkKitchenCabinet1_2.geometry}
          material={materials.MarbleMarbleSinkKitchenCabinet1}
        />
      </group>
      <mesh
        geometry={nodes.FaucetLever1MarbleSinkKitchenCabinet1.geometry}
        material={materials.MetalFaucetLever1MarbleSinkKitchenCabinet1}
        position={[0.067, 0.419, -0.287]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.FaucetSpout1MarbleSinkKitchenCabinet1.geometry}
        material={materials.MetalFaucetSpout1MarbleSinkKitchenCabinet1}
        position={[-0.011, 0.541, -0.287]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[0.449, -0.067, 0.265]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.DoorL1MarbleSinkKitchenCabinet1_1.geometry}
          material={materials.WoodDoorL1MarbleSinkKitchenCabinet1}
        />
        <mesh
          geometry={nodes.DoorL1MarbleSinkKitchenCabinet1_2.geometry}
          material={materials.MetalDoorL1MarbleSinkKitchenCabinet1}
        />
      </group>
      <group position={[-0.449, -0.067, 0.265]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.DoorR1MarbleSinkKitchenCabinet1_1.geometry}
          material={materials.WoodDoorR1MarbleSinkKitchenCabinet1}
        />
        <mesh
          geometry={nodes.DoorR1MarbleSinkKitchenCabinet1_2.geometry}
          material={materials.MetalDoorR1MarbleSinkKitchenCabinet1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Sink Kitchen Cabinet.glb");
