/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Skateboard.glb -o /workspaces/windgapacademy/components/CityPackModels/Skateboard.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Skateboard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Skateboard_Mesh.geometry} material={materials.Skateboard_Mat} />
    </group>
  )
}

useGLTF.preload('/Skateboard.glb')
