/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Skewer Vegetables.glb -o /workspaces/windgapacademy/components/CityPackModels/Skewer Vegetables.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Skewer Vegetables.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.skewerVegetables.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.meat.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.meat_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.meat_2.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.vegetables.geometry} material={materials.green} />
      <mesh geometry={nodes.vegetables_1.geometry} material={materials.red} />
    </group>
  );
}

useGLTF.preload("/Skewer Vegetables.glb");
