/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Small Bookshelf.glb -o /workspaces/windgapacademy/components/CityPackModels/Small Bookshelf.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Small Bookshelf.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SmallBookShelf1.geometry} material={materials.WoodSmallBookShelf1} position={[0, 0.344, -0.018]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Drawer1_SmallBookShelf1.geometry} material={materials.WoodDrawer1_SmallBookShelf1} position={[0, -0.443, 0.031]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Drawer2_SmallBookShelf1.geometry} material={materials.WoodDrawer2_SmallBookShelf1} position={[0, -0.755, 0.031]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Small Bookshelf.glb')
