/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Small Wardrobe.glb -o /workspaces/windgapacademy/components/CityPackModels/Small Wardrobe.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Small Wardrobe.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SmallWardrobe1.geometry} material={materials.Wood1SmallWardrobe1} position={[0, 0.218, -0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <group position={[-0.601, 0.628, 0.012]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.DoorRIght1_SmallWardrobe1_1.geometry} material={materials.Wood1DoorRIght1_SmallWardrobe1} />
        <mesh geometry={nodes.DoorRIght1_SmallWardrobe1_2.geometry} material={materials.Metal1DoorRIght1_SmallWardrobe1} />
      </group>
      <group position={[0.601, 0.628, 0.012]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.DoorLeft1_SmallWardrobe1_1.geometry} material={materials.Wood1DoorLeft1_SmallWardrobe1} />
        <mesh geometry={nodes.DoorLeft1_SmallWardrobe1_2.geometry} material={materials.Metal1DoorLeft1_SmallWardrobe1} />
      </group>
      <group position={[0, -0.125, 0.028]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer1_SmallWardrobe1_1.geometry} material={materials.Wood1Drawer1_SmallWardrobe1} />
        <mesh geometry={nodes.Drawer1_SmallWardrobe1_2.geometry} material={materials.Metal1Drawer1_SmallWardrobe1} />
      </group>
      <group position={[0, -0.357, 0.028]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Drawer2_SmallWardrobe1_1.geometry} material={materials.Wood1Drawer2_SmallWardrobe1} />
        <mesh geometry={nodes.Drawer2_SmallWardrobe1_2.geometry} material={materials.Metal1Drawer2_SmallWardrobe1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Small Wardrobe.glb')
