/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Soda.glb -o /workspaces/windgapacademy/components/CityPackModels/Soda.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Soda.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.soda_1.geometry} material={materials.purple} />
      <mesh geometry={nodes.soda_1_1.geometry} material={materials._defaultMat} />
    </group>
  );
}

useGLTF.preload("/Soda.glb");
