/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Soda Glass.glb -o /workspaces/windgapacademy/components/CityPackModels/Soda Glass.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Soda Glass.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.straw.geometry} material={materials.green} />
      <mesh geometry={nodes.sodaGlass_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.sodaGlass_1_1.geometry} material={materials.purple} />
      <mesh geometry={nodes.lemon_1.geometry} material={materials.yellow} />
      <mesh geometry={nodes.lemon_1_1.geometry} material={materials.brownLight} />
    </group>
  )
}

useGLTF.preload('/Soda Glass.glb')
