/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Speaker.glb -o /workspaces/windgapacademy/components/CityPackModels/Speaker.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Speaker.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={100}>
        <mesh geometry={nodes.speaker003_1.geometry} material={materials["Material.013"]} />
        <mesh geometry={nodes.speaker003_2.geometry} material={materials["Material.001"]} />
        <mesh geometry={nodes.speaker003_3.geometry} material={materials.BlackStruss} />
        <mesh geometry={nodes.speaker003_4.geometry} material={materials["Material.014"]} />
      </group>
    </group>
  );
}

useGLTF.preload("/Speaker.glb");
