/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Speaker-7EmeFe3O7GQ.glb -o /workspaces/windgapacademy/components/CityPackModels/Speaker-7EmeFe3O7GQ.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Speaker-7EmeFe3O7GQ.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh437030597.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh437030597_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh437030597_2.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh437030597_3.geometry} material={materials.mat22} />
    </group>
  );
}

useGLTF.preload("/Speaker-7EmeFe3O7GQ.glb");
