/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Stag.glb -o /workspaces/windgapacademy/components/CityPackModels/Stag.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Stag.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="AnimalArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group name="Stag" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Stag_1" geometry={nodes.Stag_1.geometry} material={materials['Material.003']} skeleton={nodes.Stag_1.skeleton} />
            <skinnedMesh name="Stag_2" geometry={nodes.Stag_2.geometry} material={materials.Material} skeleton={nodes.Stag_2.skeleton} />
            <skinnedMesh name="Stag_3" geometry={nodes.Stag_3.geometry} material={materials['Material.010']} skeleton={nodes.Stag_3.skeleton} />
            <skinnedMesh name="Stag_4" geometry={nodes.Stag_4.geometry} material={materials['Material.001']} skeleton={nodes.Stag_4.skeleton} />
            <skinnedMesh name="Stag_5" geometry={nodes.Stag_5.geometry} material={materials['Material.011']} skeleton={nodes.Stag_5.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Stag.glb')
