/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Stapler.glb -o /workspaces/windgapacademy/components/CityPackModels/Stapler.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Stapler.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box001.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box002.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box003.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box004.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box005.geometry} material={materials["02___Default"]} />
    </group>
  );
}

useGLTF.preload("/Stapler.glb");
