/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Statue-0Mkdl3SJDT.glb -o /workspaces/windgapacademy/components/CityPackModels/Statue-0Mkdl3SJDT.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Statue-0Mkdl3SJDT.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Statue7.geometry} material={materials.Statue7} />
    </group>
  );
}

useGLTF.preload("/Statue-0Mkdl3SJDT.glb");
