/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Statue-JXmywADgSk.glb -o /workspaces/windgapacademy/components/CityPackModels/Statue-JXmywADgSk.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Statue-JXmywADgSk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Statue6.geometry} material={materials.Statue6} />
    </group>
  )
}

useGLTF.preload('/Statue-JXmywADgSk.glb')
