/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Steamer.glb -o /workspaces/windgapacademy/components/CityPackModels/Steamer.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Steamer.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lid.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.layer_3.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.layer_3_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.layer_3_2.geometry} material={materials.green} />
      <mesh geometry={nodes.layer_4.geometry} material={materials.green} />
      <mesh geometry={nodes.layer_4_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.layer_4_2.geometry} material={materials.brown} />
      <mesh geometry={nodes.layer_5.geometry} material={materials.green} />
      <mesh geometry={nodes.layer_5_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.layer_5_2.geometry} material={materials.brown} />
    </group>
  )
}

useGLTF.preload('/Steamer.glb')
