/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Steel Sink Kitchen Cabinet.glb -o /workspaces/windgapacademy/components/CityPackModels/Steel Sink Kitchen Cabinet.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Steel Sink Kitchen Cabinet.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.449, -0.067, 0.265]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.DoorR1SteelSinkKitchenCabinet1_1.geometry}
          material={materials.WoodDoorR1SteelSinkKitchenCabinet1}
        />
        <mesh
          geometry={nodes.DoorR1SteelSinkKitchenCabinet1_2.geometry}
          material={materials.MetalDoorR1SteelSinkKitchenCabinet1}
        />
      </group>
      <group position={[0.449, -0.067, 0.265]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.DoorL1SteelSinkKitchenCabinet1_1.geometry}
          material={materials.WoodDoorL1SteelSinkKitchenCabinet1}
        />
        <mesh
          geometry={nodes.DoorL1SteelSinkKitchenCabinet1_2.geometry}
          material={materials.MetalDoorL1SteelSinkKitchenCabinet1}
        />
      </group>
      <group position={[0.062, 0.191, -0.045]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.SteelSinkKitchenCabinet1_1.geometry}
          material={materials.SteelSteelSinkKitchenCabinet1}
        />
        <mesh
          geometry={nodes.SteelSinkKitchenCabinet1_2.geometry}
          material={materials.WoodSteelSinkKitchenCabinet1}
        />
      </group>
      <mesh
        geometry={nodes.FaucetSpout1SteelSinkKitchenCabinet1.geometry}
        material={materials.MetalFaucetSpout1SteelSinkKitchenCabinet1}
        position={[0.117, 0.548, -0.275]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.FaucetLever1SteelSinkKitchenCabinet1.geometry}
        material={materials.MetalFaucetLever1SteelSinkKitchenCabinet1}
        position={[0.195, 0.426, -0.275]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Steel Sink Kitchen Cabinet.glb");
