/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Sticky notes.glb -o /workspaces/windgapacademy/components/CityPackModels/Sticky notes.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Sticky notes.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box007.geometry} material={materials['09___Default']} />
      <mesh geometry={nodes.Box008.geometry} material={materials['02___Default']} />
      <mesh geometry={nodes.Box009.geometry} material={materials['03___Default']} />
      <mesh geometry={nodes.Box010.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box011.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box012.geometry} material={materials['08___Default']} />
    </group>
  )
}

useGLTF.preload('/Sticky notes.glb')
