/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Storage Crate.glb -o /workspaces/windgapacademy/components/CityPackModels/Storage Crate.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Storage Crate.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh1_Component_2_1_Group1_Model.geometry} material={materials._8} />
      <mesh geometry={nodes.Mesh2_Component_2_2_Group1_Model.geometry} material={materials._8} />
      <mesh geometry={nodes.Mesh3_Component_2_3_Group1_Model.geometry} material={materials._8} />
      <mesh geometry={nodes.Mesh4_Component_2_4_Group1_Model.geometry} material={materials._8} />
    </group>
  );
}

useGLTF.preload("/Storage Crate.glb");
