/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Strawberry.glb -o /workspaces/windgapacademy/components/CityPackModels/Strawberry.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Strawberry.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.strawberry_1.geometry} material={materials.red} />
      <mesh geometry={nodes.strawberry_1_1.geometry} material={materials.green} />
      <mesh geometry={nodes.strawberry_1_2.geometry} material={materials.brownLight} />
    </group>
  )
}

useGLTF.preload('/Strawberry.glb')
