/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Styrofoam.glb -o /workspaces/windgapacademy/components/CityPackModels/Styrofoam.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Styrofoam.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.styrofoam.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.lid.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/Styrofoam.glb')
