/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Styrofoam Dinner.glb -o /workspaces/windgapacademy/components/CityPackModels/Styrofoam Dinner.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Styrofoam Dinner.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lid.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.styrofoamDinner_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.styrofoamDinner_1_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.styrofoamDinner_1_2.geometry} material={materials.green} />
      <mesh geometry={nodes.styrofoamDinner_1_3.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.styrofoamDinner_1_4.geometry} material={materials.greenDark} />
    </group>
  )
}

useGLTF.preload('/Styrofoam Dinner.glb')
