/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Sub.glb -o /workspaces/windgapacademy/components/CityPackModels/Sub.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Sub.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sub_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.sub_1_1.geometry} material={materials.brown} />
      <mesh geometry={nodes.Group_1.geometry} material={materials.red} />
      <mesh geometry={nodes.Group_1_1.geometry} material={materials.redLight} />
      <mesh geometry={nodes.lettuce_1.geometry} material={materials.green} />
      <mesh geometry={nodes.lettuce_1_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.meat_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.meat_1_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.tomaties_3.geometry} material={materials.red} />
      <mesh geometry={nodes.tomaties_3_1.geometry} material={materials.redLight} />
      <mesh geometry={nodes.tomaties_4.geometry} material={materials.redLight} />
      <mesh geometry={nodes.tomaties_4_1.geometry} material={materials.red} />
      <mesh geometry={nodes.tomaties_5.geometry} material={materials.redLight} />
      <mesh geometry={nodes.tomaties_5_1.geometry} material={materials.red} />
    </group>
  );
}

useGLTF.preload("/Sub.glb");
