/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Sundae.glb -o /workspaces/windgapacademy/components/CityPackModels/Sundae.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Sundae.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.straw.geometry} material={materials.green} />
      <mesh geometry={nodes.sundae_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.sundae_1_1.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.sundae_1_2.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.cherry_1.geometry} material={materials.red} />
      <mesh geometry={nodes.cherry_1_1.geometry} material={materials.green} />
    </group>
  );
}

useGLTF.preload("/Sundae.glb");
