/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Sushi Egg.glb -o /workspaces/windgapacademy/components/CityPackModels/Sushi Egg.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Sushi Egg.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sushiEgg_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.sushiEgg_1_1.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.egg_1.geometry} material={materials.brownDarkest} />
      <mesh geometry={nodes.egg_1_1.geometry} material={materials.yellow} />
    </group>
  );
}

useGLTF.preload("/Sushi Egg.glb");
