/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Sushi Salmon.glb -o /workspaces/windgapacademy/components/CityPackModels/Sushi Salmon.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Sushi Salmon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sushiSalmon.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.salmon_1.geometry} material={materials.orange} />
      <mesh geometry={nodes.salmon_1_1.geometry} material={materials.brownLight} />
    </group>
  )
}

useGLTF.preload('/Sushi Salmon.glb')
