/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/SUV.glb -o /workspaces/windgapacademy/components/CityPackModels/SUV.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/SUV.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['SUV_Cube-Mesh'].geometry} material={materials.White} />
      <mesh geometry={nodes['SUV_Cube-Mesh_1'].geometry} material={materials.Windows} />
      <mesh geometry={nodes['SUV_Cube-Mesh_2'].geometry} material={materials.Black} />
      <mesh geometry={nodes['SUV_Cube-Mesh_3'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['SUV_Cube-Mesh_4'].geometry} material={materials.Headlights} />
      <mesh geometry={nodes['SUV_Cube-Mesh_5'].geometry} material={materials.TailLights} />
      <mesh geometry={nodes['SUV_BackWheels_Cylinder009-Mesh'].geometry} material={materials.Black} />
      <mesh geometry={nodes['SUV_BackWheels_Cylinder009-Mesh_1'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['SUV_FrontLeftWheel_Cylinder010-Mesh'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['SUV_FrontLeftWheel_Cylinder010-Mesh_1'].geometry} material={materials.Black} />
      <mesh geometry={nodes['SUV_FrontRightWheel_Cylinder005-Mesh'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['SUV_FrontRightWheel_Cylinder005-Mesh_1'].geometry} material={materials.Black} />
    </group>
  )
}

useGLTF.preload('/SUV.glb')
