/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Table-MuBw2WmVTU.glb -o /workspaces/windgapacademy/components/CityPackModels/Table-MuBw2WmVTU.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Table-MuBw2WmVTU.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Table2.geometry} material={materials.Table2} />
    </group>
  );
}

useGLTF.preload("/Table-MuBw2WmVTU.glb");
