/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Table-wAaFESADdd.glb -o /workspaces/windgapacademy/components/CityPackModels/Table-wAaFESADdd.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Table-wAaFESADdd.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Table3.geometry} material={materials.Table3} />
    </group>
  );
}

useGLTF.preload("/Table-wAaFESADdd.glb");
