/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Table Tennis Paddle.glb -o /workspaces/windgapacademy/components/CityPackModels/Table Tennis Paddle.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Table Tennis Paddle.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Table_Tennis_Paddle_Cube033_1.geometry} material={materials.DD9944} />
      <mesh
        geometry={nodes.Table_Tennis_Paddle_Cube033_1_1.geometry}
        material={materials["1A1A1A"]}
      />
      <mesh geometry={nodes.Table_Tennis_Paddle_Cube033_1_2.geometry} material={materials.F44336} />
    </group>
  );
}

useGLTF.preload("/Table Tennis Paddle.glb");
