/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Table Lamp.glb -o /workspaces/windgapacademy/components/CityPackModels/Table Lamp.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Table Lamp.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.TableLamp1_1.geometry} material={materials.MetalTableLamp1} />
        <mesh geometry={nodes.TableLamp1_2.geometry} material={materials.ShadeTableLamp1} />
        <mesh geometry={nodes.TableLamp1_3.geometry} material={materials.LightTableLamp1} />
      </group>
    </group>
  );
}

useGLTF.preload("/Table Lamp.glb");
