/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Table Large Circular.glb -o /workspaces/windgapacademy/components/CityPackModels/Table Large Circular.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Table Large Circular.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Table_large_circular.geometry}
        material={materials.Material}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Table Large Circular.glb");
