/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Table tennis table.glb -o /workspaces/windgapacademy/components/CityPackModels/Table tennis table.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Table tennis table.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box124.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box125.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box126.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box127.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box128.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box129.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box130.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box131.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box132.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box133.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box134.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box135.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box136.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box137.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box138.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box139.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box140.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box141.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box142.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box143.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box144.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box145.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box146.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box147.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box148.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box149.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box150.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box151.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box152.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box153.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box154.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box155.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box156.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box157.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box158.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box159.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box160.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box161.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box162.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box163.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box164.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box165.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box166.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box167.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box168.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box169.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box170.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box171.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box172.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box173.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box174.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box175.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box176.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box177.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box178.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box179.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box180.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box181.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box182.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box183.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box184.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box185.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box186.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box187.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box188.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box189.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box190.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box191.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box192.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box193.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box194.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box195.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box196.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box197.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box198.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box199.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box200.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box201.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box202.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box203.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box204.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box205.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box206.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box207.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box208.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box209.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box210.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box211.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box212.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box213.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box214.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box215.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box216.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box217.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box218.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box219.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box220.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box221.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box222.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box223.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box224.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box225.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box226.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box227.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box228.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box229.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box230.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box231.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box232.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box233.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box234.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box235.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box236.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box237.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box238.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box239.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box240.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box241.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box242.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box243.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box244.geometry} material={materials["02___Default"]} />
      <mesh geometry={nodes.Box123_1.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Box123_1_1.geometry} material={materials["02___Default"]} />
    </group>
  );
}

useGLTF.preload("/Table tennis table.glb");
