/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Taco.glb -o /workspaces/windgapacademy/components/CityPackModels/Taco.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Taco.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.taco_1.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.taco_1_1.geometry} material={materials.yellow} />
      <mesh geometry={nodes.taco_1_2.geometry} material={materials.red} />
      <mesh geometry={nodes.taco_1_3.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.taco_1_4.geometry} material={materials.green} />
    </group>
  );
}

useGLTF.preload("/Taco.glb");
