/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Tall Grass.glb -o /workspaces/windgapacademy/components/CityPackModels/Tall Grass.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Tall Grass.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grass_Common_Tall.geometry} material={materials.Grass} />
    </group>
  );
}

useGLTF.preload("/Tall Grass.glb");
