/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Tea Cup.glb -o /workspaces/windgapacademy/components/CityPackModels/Tea Cup.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Tea Cup.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TeaCup1.geometry} material={materials.PorcelainTeaCup1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Plate1TeaCup1.geometry} material={materials.PorcelainPlateTeaCup1} position={[0, -0.062, 0.026]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Tea Cup.glb')
