/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Three Seater Couch.glb -o /workspaces/windgapacademy/components/CityPackModels/Three Seater Couch.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Three Seater Couch.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ThreeSeaterCouch1.geometry} material={materials.ThreeSeaterCouch1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Pad4ThreeSeaterCouch1.geometry} material={materials.Pad4ThreeSeaterCouch1} position={[-0.701, -0.094, 0.153]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Pad5ThreeSeaterCouch1.geometry} material={materials.Pad5ThreeSeaterCouch1} position={[0.005, -0.094, 0.153]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Pad6ThreeSeaterCouch1.geometry} material={materials.Pad6ThreeSeaterCouch1} position={[0.718, -0.094, 0.153]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Pad1ThreeSeaterCouch1.geometry} material={materials.Pad1ThreeSeaterCouch1} position={[-0.696, 0.317, -0.233]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Pad2ThreeSeaterCouch1.geometry} material={materials.Pad2ThreeSeaterCouch1} position={[0.002, 0.317, -0.233]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Pad3ThreeSeaterCouch1.geometry} material={materials.Pad3ThreeSeaterCouch1} position={[0.715, 0.317, -0.233]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Three Seater Couch.glb')
