/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/TIME HOTEL 3.16.glb -o /workspaces/windgapacademy/components/CityPackModels/TIME HOTEL 3.16.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/TIME HOTEL 3.16.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group913992076.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group202920538.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1082469960.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group301368041.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1355480681.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1152017475.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1152017475_1.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1152017475_2.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1152017475_3.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1152017475_4.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh1775406409.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1775406409_1.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1775406409_2.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1884494935.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1884494935_1.geometry} material={materials.mat8} />
    </group>
  );
}

useGLTF.preload("/TIME HOTEL 3.16.glb");
