/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/TIME HOTEL 4.06.glb -o /workspaces/windgapacademy/components/CityPackModels/TIME HOTEL 4.06.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/TIME HOTEL 4.06.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group812305468.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1692528657.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1209406790.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1209406790_1.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1209406790_2.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1209406790_3.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1209406790_4.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1209406790_5.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1209406790_6.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh979327674.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh979327674_1.geometry} material={materials.mat23} />
    </group>
  );
}

useGLTF.preload("/TIME HOTEL 4.06.glb");
