/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Tissue Box.glb -o /workspaces/windgapacademy/components/CityPackModels/Tissue Box.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Tissue Box.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tissue_Box.geometry} material={materials.Material} scale={100} />
    </group>
  );
}

useGLTF.preload("/Tissue Box.glb");
