/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Toaster.glb -o /workspaces/windgapacademy/components/CityPackModels/Toaster.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Toaster.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Toaster1.geometry}
        material={materials.MetalToaster1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.ToasterLever1Toaster1.geometry}
        material={materials.SteelToasterLever1Toaster1}
        position={[-0.183, -0.081, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Toaster.glb");
