/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Toilet Paper stack.glb -o /workspaces/windgapacademy/components/CityPackModels/Toilet Paper stack.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Toilet Paper stack.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Bathroom_ToiletPaperPile_1.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Bathroom_ToiletPaperPile_2.geometry} material={materials.White} />
      </group>
    </group>
  );
}

useGLTF.preload("/Toilet Paper stack.glb");
