/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Tomato Slice.glb -o /workspaces/windgapacademy/components/CityPackModels/Tomato Slice.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Tomato Slice.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tomatoSlice_1.geometry} material={materials.red} />
      <mesh geometry={nodes.tomatoSlice_1_1.geometry} material={materials.redLight} />
    </group>
  );
}

useGLTF.preload("/Tomato Slice.glb");
