/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Top hat.glb -o /workspaces/windgapacademy/components/CityPackModels/Top hat.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Top hat.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Node-Mesh"].geometry} material={materials.lambert3SG} />
      <mesh geometry={nodes["Node-Mesh_1"].geometry} material={materials.lambert2SG} />
    </group>
  );
}

useGLTF.preload("/Top hat.glb");
