/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Towel Rack.glb -o /workspaces/windgapacademy/components/CityPackModels/Towel Rack.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Towel Rack.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Bathroom_Towel_1.geometry} material={materials.LightMetal} />
        <mesh geometry={nodes.Bathroom_Towel_2.geometry} material={materials.White} />
        <mesh geometry={nodes.Bathroom_Towel_3.geometry} material={materials.Red} />
      </group>
    </group>
  );
}

useGLTF.preload("/Towel Rack.glb");
