/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Traffic Light.glb -o /workspaces/windgapacademy/components/CityPackModels/Traffic Light.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Traffic Light.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.TrafficLight_2.geometry}
        material={materials["Atlas.052"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Traffic Light.glb");
