/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/trah bag grey.glb -o /workspaces/windgapacademy/components/CityPackModels/trah bag grey.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/trah bag grey.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group104413426.geometry} material={materials.mat17} />
    </group>
  );
}

useGLTF.preload("/trah bag grey.glb");
