/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Trash Bin.glb -o /workspaces/windgapacademy/components/CityPackModels/Trash Bin.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Trash Bin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Trashbin.geometry} material={materials.Material} scale={100} />
    </group>
  )
}

useGLTF.preload('/Trash Bin.glb')
