/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Trashcan.glb -o /workspaces/windgapacademy/components/CityPackModels/Trashcan.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Trashcan.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Trashcan_Cylindric.geometry}
        material={materials.LightMetal}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Trashcan.glb");
