/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Tree-t9KbsfYdXz.glb -o /workspaces/windgapacademy/components/CityPackModels/Tree-t9KbsfYdXz.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Tree-t9KbsfYdXz.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CommonTree_5_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.CommonTree_5_2.geometry} material={materials.Leaves_NormalTree} />
    </group>
  );
}

useGLTF.preload("/Tree-t9KbsfYdXz.glb");
