/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Tree-QVOop92WmG.glb -o /workspaces/windgapacademy/components/CityPackModels/Tree-QVOop92WmG.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Tree-QVOop92WmG.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CommonTree_3_1.geometry} material={materials.Bark_NormalTree} />
      <mesh geometry={nodes.CommonTree_3_2.geometry} material={materials.Leaves_NormalTree} />
    </group>
  )
}

useGLTF.preload('/Tree-QVOop92WmG.glb')
