/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Triple Sink.glb -o /workspaces/windgapacademy/components/CityPackModels/Triple Sink.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Triple Sink.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]} scale={[0.004, 0.013, 0.013]}>
        <mesh geometry={nodes.Lathe2.geometry} material={materials.steel} />
        <mesh geometry={nodes.Lathe2_1.geometry} material={materials["Blue.001"]} />
        <mesh geometry={nodes.Lathe2_2.geometry} material={materials.steel2} />
      </group>
    </group>
  );
}

useGLTF.preload("/Triple Sink.glb");
