/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Trophy.glb -o /workspaces/windgapacademy/components/CityPackModels/Trophy.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Trophy.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Trophy_Cube024_1.geometry} material={materials.FFEB3B} />
      <mesh geometry={nodes.Trophy_Cube024_1_1.geometry} material={materials["1A1A1A"]} />
      <mesh geometry={nodes.Trophy_Cube024_1_2.geometry} material={materials.F44336} />
    </group>
  );
}

useGLTF.preload("/Trophy.glb");
