/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Two Seater Couch.glb -o /workspaces/windgapacademy/components/CityPackModels/Two Seater Couch.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Two Seater Couch.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TwoSeaterCouch1.geometry} material={materials.TwoSeaterCouch1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Pad4TwoSeaterCouch1.geometry} material={materials.Pad4TwoSeaterCouch1} position={[0.316, -0.081, 0.037]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Pad1TwoSeaterCouch1.geometry} material={materials.Pad1TwoSeaterCouch1} position={[-0.329, 0.308, -0.197]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Pad2TwoSeaterCouch1.geometry} material={materials.Pad2TwoSeaterCouch1} position={[0.316, 0.308, -0.197]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Pad3TwoSeaterCouch1.geometry} material={materials.Pad3TwoSeaterCouch1} position={[-0.316, -0.081, 0.037]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Two Seater Couch.glb')
