/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Utensil Spoon.glb -o /workspaces/windgapacademy/components/CityPackModels/Utensil Spoon.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Utensil Spoon.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.utensilSpoon.geometry} material={materials.white} />
    </group>
  );
}

useGLTF.preload("/Utensil Spoon.glb");
