/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Van.glb -o /workspaces/windgapacademy/components/CityPackModels/Van.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Van.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Van.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/Van.glb')
