/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Various Stacks of Paper.glb -o /workspaces/windgapacademy/components/CityPackModels/Various Stacks of Paper.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Various Stacks of Paper.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Node-Mesh"].geometry} material={materials.mat21} />
      <mesh geometry={nodes["Node-Mesh_1"].geometry} material={materials.mat15} />
    </group>
  );
}

useGLTF.preload("/Various Stacks of Paper.glb");
