/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Vending Machine.glb -o /workspaces/windgapacademy/components/CityPackModels/Vending Machine.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Vending Machine.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[7.607, -1, 1.042]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[245.659, 245.659, 100]}
      >
        <mesh geometry={nodes.conk_vendo_1.geometry} material={materials.F44336} />
        <mesh geometry={nodes.conk_vendo_2.geometry} material={materials.Black} />
        <mesh geometry={nodes.conk_vendo_3.geometry} material={materials["78909C"]} />
        <mesh geometry={nodes.conk_vendo_4.geometry} material={materials.Yellow} />
        <mesh geometry={nodes.conk_vendo_5.geometry} material={materials["Light gray"]} />
        <mesh geometry={nodes.conk_vendo_6.geometry} material={materials.Orange} />
        <mesh geometry={nodes.conk_vendo_7.geometry} material={materials.Green} />
      </group>
    </group>
  );
}

useGLTF.preload("/Vending Machine.glb");
