/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Volleyball Ball.glb -o /workspaces/windgapacademy/components/CityPackModels/Volleyball Ball.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Volleyball Ball.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.VolleyballBall1_1.geometry} material={materials.Yellow1VolleyballBall1} />
        <mesh geometry={nodes.VolleyballBall1_2.geometry} material={materials.Blue1VolleyballBall1} />
        <mesh geometry={nodes.VolleyballBall1_3.geometry} material={materials.White1VolleyballBall1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Volleyball Ball.glb')
