/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Waffle.glb -o /workspaces/windgapacademy/components/CityPackModels/Waffle.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Waffle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.waffle.geometry} material={materials.brownLight} />
    </group>
  )
}

useGLTF.preload('/Waffle.glb')
