/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Wall Art 06.glb -o /workspaces/windgapacademy/components/CityPackModels/Wall Art 06.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Wall Art 06.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat23} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat21} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat16} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat22} />
      <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat17} />
      <mesh geometry={nodes['Node-Mesh_5'].geometry} material={materials.mat15} />
      <mesh geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat24} />
      <mesh geometry={nodes['Node-Mesh_7'].geometry} material={materials.mat25} />
    </group>
  )
}

useGLTF.preload('/Wall Art 06.glb')
