/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Wash Brush.glb -o /workspaces/windgapacademy/components/CityPackModels/Wash Brush.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Wash Brush.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.WashBrush1_1.geometry} material={materials.Wood1WashBrush1} />
        <mesh geometry={nodes.WashBrush1_2.geometry} material={materials.Bristles1WashBrush1} />
      </group>
    </group>
  );
}

useGLTF.preload("/Wash Brush.glb");
