/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Washing Line.glb -o /workspaces/windgapacademy/components/CityPackModels/Washing Line.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Washing Line.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.988, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={48}>
        <mesh geometry={nodes.WashingLine_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.WashingLine_2.geometry} material={materials.black_plastic} />
      </group>
    </group>
  );
}

useGLTF.preload("/Washing Line.glb");
