/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Water Cooler.glb -o /workspaces/windgapacademy/components/CityPackModels/Water Cooler.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Water Cooler.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Cooler_Cylinder004-Mesh"].geometry}
        material={materials.WhitePlastic}
      />
      <mesh
        geometry={nodes["Cooler_Cylinder004-Mesh_1"].geometry}
        material={materials.BluePlastic}
      />
      <mesh geometry={nodes["Cooler_Cylinder004-Mesh_2"].geometry} material={materials.Red} />
      <mesh geometry={nodes["Cooler_Cylinder004-Mesh_3"].geometry} material={materials.Blue} />
    </group>
  );
}

useGLTF.preload("/Water Cooler.glb");
