/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Water bottle.glb -o /workspaces/windgapacademy/components/CityPackModels/Water bottle.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Water bottle.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.pasted__polySurface11_group_1.geometry}
        material={materials.blinn11SG}
      />
      <mesh
        geometry={nodes.pasted__polySurface11_group_1_1.geometry}
        material={materials.blinn6SG}
      />
    </group>
  );
}

useGLTF.preload("/Water bottle.glb");
