/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Webcam.glb -o /workspaces/windgapacademy/components/CityPackModels/Webcam.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Webcam.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.061, 0.076]} scale={100}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Dark} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials.Material} />
      </group>
    </group>
  );
}

useGLTF.preload("/Webcam.glb");
