/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Whipped Cream.glb -o /workspaces/windgapacademy/components/CityPackModels/Whipped Cream.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Whipped Cream.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.whippedCream.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/Whipped Cream.glb')
