/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Whisk.glb -o /workspaces/windgapacademy/components/CityPackModels/Whisk.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Whisk.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.whisk_1.geometry} material={materials.white} />
      <mesh geometry={nodes.whisk_1_1.geometry} material={materials.greyDark} />
    </group>
  );
}

useGLTF.preload("/Whisk.glb");
