/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Whiteboard.glb -o /workspaces/windgapacademy/components/CityPackModels/Whiteboard.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Whiteboard.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.White_board001_Cube026_1.geometry} material={materials["1A1A1A"]} />
      <mesh geometry={nodes.White_board001_Cube026_1_1.geometry} material={materials["455A64"]} />
      <mesh geometry={nodes.White_board_Cube045_1.geometry} material={materials.FFFFFF} />
      <mesh geometry={nodes.White_board_Cube045_1_1.geometry} material={materials.F44336} />
    </group>
  );
}

useGLTF.preload("/Whiteboard.glb");
