/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Whole Ham.glb -o /workspaces/windgapacademy/components/CityPackModels/Whole Ham.jsx 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Whole Ham.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.wholeHam_1.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.wholeHam_1_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.wholeHam_1_2.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.wholeHam_1_3.geometry} material={materials.orange} />
    </group>
  );
}

useGLTF.preload("/Whole Ham.glb");
