/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Wide Dresser.glb -o /workspaces/windgapacademy/components/CityPackModels/Wide Dresser.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Wide Dresser.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.WideDresser1.geometry}
        material={materials.Wood1WideDresser1}
        position={[0, -0.017, -0.041]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group position={[-0.585, 0.249, 0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer1_WideDresser1_1.geometry}
          material={materials.Wood1Drawer1_WideDresser1}
        />
        <mesh
          geometry={nodes.Drawer1_WideDresser1_2.geometry}
          material={materials.Metal1Drawer1_WideDresser1}
        />
      </group>
      <group position={[-0.214, 0.249, 0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer2_WideDresser1_1.geometry}
          material={materials.Wood1Drawer2_WideDresser1}
        />
        <mesh
          geometry={nodes.Drawer2_WideDresser1_2.geometry}
          material={materials.Metal1Drawer2_WideDresser1}
        />
      </group>
      <group position={[-0.4, 0.03, 0.186]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer3_WideDresser1_1.geometry}
          material={materials.Wood1Drawer3_WideDresser1}
        />
        <mesh
          geometry={nodes.Drawer3_WideDresser1_2.geometry}
          material={materials.Metal1Drawer3_WideDresser1}
        />
      </group>
      <group position={[-0.4, -0.25, 0.186]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer4_WideDresser1_1.geometry}
          material={materials.Wood1Drawer4_WideDresser1}
        />
        <mesh
          geometry={nodes.Drawer4_WideDresser1_2.geometry}
          material={materials.Metal1Drawer4_WideDresser1}
        />
      </group>
      <group position={[0.214, 0.249, 0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer5_WideDresser1_1.geometry}
          material={materials.Wood1Drawer5_WideDresser1}
        />
        <mesh
          geometry={nodes.Drawer5_WideDresser1_2.geometry}
          material={materials.Metal1Drawer5_WideDresser1}
        />
      </group>
      <group position={[0.585, 0.249, 0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer6_WideDresser1_1.geometry}
          material={materials.Wood1Drawer6_WideDresser1}
        />
        <mesh
          geometry={nodes.Drawer6_WideDresser1_2.geometry}
          material={materials.Metal1Drawer6_WideDresser1}
        />
      </group>
      <group position={[0.4, 0.03, 0.186]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer7_WideDresser1_1.geometry}
          material={materials.Wood1Drawer7_WideDresser1}
        />
        <mesh
          geometry={nodes.Drawer7_WideDresser1_2.geometry}
          material={materials.Metal1Drawer7_WideDresser1}
        />
      </group>
      <group position={[0.4, -0.25, 0.186]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Drawer8_WideDresser1_1.geometry}
          material={materials.Wood1Drawer8_WideDresser1}
        />
        <mesh
          geometry={nodes.Drawer8_WideDresser1_2.geometry}
          material={materials.Metal1Drawer8_WideDresser1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Wide Dresser.glb");
