/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Window Blinds.glb -o /workspaces/windgapacademy/components/CityPackModels/Window Blinds.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Window Blinds.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group427675855.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1606767967.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1246942833.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group970697144.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group848587833.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1840719534.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1477700025.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1856349250.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group298871933.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1512631129.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1103958513.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh1103958513_1.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh205479027.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh205479027_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh1774544435.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1774544435_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh2011576104.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh2011576104_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh1024187379.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh1024187379_1.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1785529362.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1785529362_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh451389640.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh451389640_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh928384235.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh928384235_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh765891613.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh765891613_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh491062930.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh491062930_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh830606209.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh830606209_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh11767427.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh11767427_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh1614564418.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh1614564418_1.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh77709967.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh77709967_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh77709967_2.geometry} material={materials.mat17} />
    </group>
  );
}

useGLTF.preload("/Window Blinds.glb");
