/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Wolf.glb -o /workspaces/windgapacademy/components/CityPackModels/Wolf.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Wolf.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="AnimalArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group name="Wolf" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Wolf_1" geometry={nodes.Wolf_1.geometry} material={materials.Main} skeleton={nodes.Wolf_1.skeleton} />
            <skinnedMesh name="Wolf_2" geometry={nodes.Wolf_2.geometry} material={materials.Main_Light} skeleton={nodes.Wolf_2.skeleton} />
            <skinnedMesh name="Wolf_3" geometry={nodes.Wolf_3.geometry} material={materials.Eyes_Black} skeleton={nodes.Wolf_3.skeleton} />
            <skinnedMesh name="Wolf_4" geometry={nodes.Wolf_4.geometry} material={materials.Nose} skeleton={nodes.Wolf_4.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Wolf.glb')
