/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Wooden Arm Chair.glb -o /workspaces/windgapacademy/components/CityPackModels/Wooden Arm Chair.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Wooden Arm Chair.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.WoodArmChair1.geometry} material={materials.WoodArmChair1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Pad2WoodArmChair1.geometry} material={materials.Pad2WoodArmChair1} position={[0.002, -0.094, 0.153]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Pad1WoodArmChair1.geometry} material={materials.Pad1WoodArmChair1} position={[0.008, 0.317, -0.233]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Wooden Arm Chair.glb')
