/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Wooden Chair.glb -o /workspaces/windgapacademy/components/CityPackModels/Wooden Chair.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Wooden Chair.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.WoodenChair1_1.geometry} material={materials.Cloth1WoodenChair1} />
        <mesh geometry={nodes.WoodenChair1_2.geometry} material={materials.Wood1WoodenChair1} />
      </group>
    </group>
  )
}

useGLTF.preload('/Wooden Chair.glb')
