/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Wood Kitchen Chair.glb -o /workspaces/windgapacademy/components/CityPackModels/Wood Kitchen Chair.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Wood Kitchen Chair.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.WoodKitchenChair.geometry}
        material={materials.WoodWoodKitchenChair}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Wood Kitchen Chair.glb");
