/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Wool Carpet.glb -o /workspaces/windgapacademy/components/CityPackModels/Wool Carpet.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Wool Carpet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.WoolCarpet1.geometry} material={materials.WoolCarpet1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Wool Carpet.glb')
