/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /workspaces/windgapacademy/backend/api/citypack/unpacked/Yellow Post-it.glb -o /workspaces/windgapacademy/components/CityPackModels/Yellow Post-it.jsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Yellow Post-it.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1376193121.geometry} material={materials.mat12} />
    </group>
  );
}

useGLTF.preload("/Yellow Post-it.glb");
