// Speech recognition mappings for Windgap Academy
// Generated from user-provided Python dictionaries

export const letterMap = {
    "acid": "a",
    "bony": "b",
    "char": "c",
    "dozen": "d",
    "ebike": "e",
    "foxy": "f",
    "golf": "g",
    "hotel": "h",
    "itchy": "i",
    "julia": "j",
    "krife": "k",
    "lazy": "l",
    "miley": "m",
    "nasal": "n",
    "odin": "o",
    "premier": "p",
    "queen": "q",
    "remo": "r",
    "salty": "s",
    "tosh": "t",
    "unix": "u",
    "video": "v",
    "wages": "w",
    "x-ray": "x",
    "yoke": "y",
    "zimeesi": "z"
};

export const punctuationMap1 = {
    "tilda": "~",
    "quotes": '"',
    "at": "@",
    "hash": "#",
    "dollar": "$",
    "percent": "%",
    "caret": "^",
    "plus": "+",
    "minus": "-",
    "equals": "=",
    "colon": ":",
    "slash": "/",
    "pipe": "|",
    "comma": ",",
    "dot": ".",
    "question": "?"
};

export const punctuationMap2 = {
    "underscore": "_",
    "semicolon": ";",
    "backtick": "`",
    "exclamation": "!",
    "ampersand": "&",
    "asterisk": "*",
    "backslash": "\\",
    "round bracket": "(",
    "close round": ")",
    "square bracket": "[",
    "close square": "]",
    "curly brace": "{",
    "close curly": "}",
    "less than": "<",
    "greater than": ">"
};

export const longPunctuationMap = {
    "pipe symbol": "|",
    "minus": "-",
    "dot": ".",
    "comma": ",",
    "backslash": "\\",
    "underscore": "_",
    "(asterisk|Asterix)": "*",
    "colon": ":",
    "(semicolon|semi colon)": ";",
    "at symbol": "@",
    "quotes": '"',
    "single quote": "'",
    "apostrophe": "'",
    "hash": "#",
    "dollar": "$",
    "dollar sign": "$",
    "percent": "%",
    "percentage": "%",
    "ampersand": "&",
    "slash": "/",
    "equals": "=",
    "plus": "+",
    "space": " ",
    "question": "?",
    "question mark": "?",
    "exclamation": "!",
    "exclamation mark": "!",
    "caret": "^",
    "tilde": "~",
    "back tick": "`"
};
