name: Submodule Setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
      # Add additional steps here if needed
